/* New R01 native viewer. Presentation animation only, no functional weapon simulation. */
(async function(){
 const T=THREE,$=id=>document.getElementById(id),V=(x,y,z)=>new T.Vector3(x,y,z),VERSION='wm.aircraft.native-r01.20260906';
 const state={spread:0,time:0,playing:false,speed:1,selected:null,solo:null,hidden:[],mode:'surface',light:'studio',comparison:false,orbit:false};
 const DURATION=12,PERIOD=.12,CAPACITY=10;let ticks=0,last=performance.now(),lastUI=0,boxHelper=null,tween=null,raf=0;const errors=[];
 const reportError=e=>{errors.push(String(e.message||e));$('loading').hidden=true;$('error').hidden=false;$('error').textContent='工作台未完成加载：'+String(e.message||e);};
 addEventListener('error',e=>reportError(e.error||e.message));addEventListener('unhandledrejection',e=>reportError(e.reason));
 try{
 const renderer=new T.WebGLRenderer({canvas:$('canvas'),antialias:true,alpha:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.setClearColor(0x000000,0);
 const scene=new T.Scene(),camera=new T.PerspectiveCamera(32,1,.02,120);camera.up.set(0,1,0);const controls=new OrbitControls(camera,$('canvas'));controls.enableDamping=true;controls.dampingFactor=.10;controls.minDistance=1.1;controls.maxDistance=40;controls.maxPolarAngle=Math.PI*.87;controls.autoRotateSpeed=.4;
 const surfaces=createSurfaces(T),asset=buildAircraft(T,surfaces.materials);scene.add(asset.root);const stats=asset.geometryStats();
 // Keep the decorative box flush with the display platform, without changing gun orientation.
 const feedPart=asset.parts.find(p=>p.name==='feed');feedPart.position.y=.07;feedPart.userData.rest.y=.07;
 const key=new T.DirectionalLight(0xffefd6,3.0);key.position.set(-1,7,5);key.castShadow=true;key.shadow.mapSize.set(1536,1536);Object.assign(key.shadow.camera,{left:-7,right:7,top:5,bottom:-5,near:.2,far:30});key.shadow.normalBias=.023;key.shadow.bias=-.0002;
 const fill=new T.DirectionalLight(0xd6e9ff,1.3);fill.position.set(0,3,-6);const rim=new T.DirectionalLight(0xf0eee8,2.2);rim.position.set(5,5,-3);const ambient=new T.HemisphereLight(0xc9d6e0,0x303330,.65);scene.add(key,fill,rim,ambient);
 // Generated light environment and shadow buffers are transient renderer resources.
 const env=new T.Scene();env.background=new T.Color(.12,.13,.14);env.add(new T.Mesh(new T.BoxGeometry(30,30,30),new T.MeshBasicMaterial({color:0x52565a,side:T.BackSide})));
 for(const [pos,w,h,power]of [[[0,9,4],12,5,4],[[-7,3,4],4,6,2.3],[[6,3,-4],8,3,3]]){const m=new T.Mesh(new T.PlaneGeometry(w,h),new T.MeshBasicMaterial({color:new T.Color(1,.98,.93).multiplyScalar(power),side:T.DoubleSide}));m.position.set(...pos);m.lookAt(0,0,0);env.add(m);}
 const pmrem=new T.PMREMGenerator(renderer),envTarget=pmrem.fromScene(env,.12,.1,50);scene.environment=envTarget.texture;scene.environmentIntensity=.7;pmrem.dispose();env.traverse(o=>{o.geometry?.dispose();o.material?.dispose();});
 const stageBase=new T.Mesh(new T.CylinderGeometry(5.8,5.8,.20,96),new T.MeshStandardMaterial({color:0x252e35,metalness:.18,roughness:.74}));stageBase.scale.z=.47;stageBase.position.set(.1,-.20,.25);stageBase.receiveShadow=true;scene.add(stageBase);
 const floor=new T.Mesh(new T.PlaneGeometry(200,200),new T.ShadowMaterial({opacity:.24}));floor.rotation.x=-Math.PI/2;floor.position.y=-.315;floor.receiveShadow=true;scene.add(floor);
 const fx=new T.Group();fx.name='presentation.effects';scene.add(fx);
 const cases=new T.InstancedMesh(asset.caseGeo,surfaces.materials.brass,CAPACITY),links=new T.InstancedMesh(asset.linkGeo,surfaces.materials.steel,CAPACITY);cases.castShadow=true;links.castShadow=true;fx.add(cases,links);
 const flashes=[];const lightFlash=new T.PointLight(0xffb354,0,3.5);lightFlash.position.copy(asset.muzzle);fx.add(lightFlash);
 const flashMat=new T.MeshBasicMaterial({color:0xffcf7b,transparent:true,opacity:.6,depthWrite:false,blending:T.AdditiveBlending});const flash=new T.Mesh(new T.SphereGeometry(1,12,8),flashMat);flash.position.copy(asset.muzzle);flash.scale.set(.16,.05,.05);fx.add(flash);
 const trails=[];for(let i=0;i<3;i++){const mat=new T.MeshBasicMaterial({color:0xffb14b,transparent:true,opacity:.85,depthWrite:false,blending:T.AdditiveBlending});const m=new T.Mesh(new T.CylinderGeometry(.009,.013,.6,8),mat);m.rotation.z=-Math.PI/2;m.visible=false;fx.add(m);trails.push(m);}
 const scratch=new T.Object3D();
 function events(t){if(t>=DURATION||state.spread>0)return [];const last=Math.floor(t/PERIOD+1e-8);const out=[];for(let i=Math.max(1,last-CAPACITY+1);i<=last;i++){const age=t-i*PERIOD;if(age>=-1e-8&&age<1.15)out.push({index:i,age:Math.max(0,age),tracer:i%5===0});}return out;}
 function updateFx(){const es=events(state.time);cases.count=es.length;links.count=es.length;trails.forEach(m=>m.visible=false);flash.visible=false;lightFlash.intensity=0;let ti=0;
 for(let j=0;j<es.length;j++){const e=es[j],a=e.age;const k=Math.min(a/.75,1),side=e.index%2?1:-1;const y=Math.max(-.025,.82-1.1*k*k);
 scratch.position.set(-1.54+.55*k,y,-.49-.32*k);scratch.rotation.set(a*8,side*a*3,a*4);scratch.scale.set(.7,.7,.7);scratch.updateMatrix();cases.setMatrixAt(j,scratch.matrix);
 scratch.position.set(-.91+.22*k,Math.max(-.045,.9-1.2*k*k),.52+.24*k);scratch.rotation.set(a*5,a*4,a*3);scratch.scale.set(.75,.75,.75);scratch.updateMatrix();links.setMatrixAt(j,scratch.matrix);
 if(a<.033){flash.visible=true;flash.scale.set(.12+.9*(.033-a),.045,.045);lightFlash.intensity=1.2;}
 if(e.tracer&&a<.22&&ti<trails.length){const m=trails[ti++];m.visible=true;m.position.copy(asset.muzzle).add(V(.15+a*12,0,0));m.material.opacity=(1-a/.22)*.95;}
 }
 cases.instanceMatrix.needsUpdate=true;links.instanceMatrix.needsUpdate=true;fx.visible=state.spread===0&&es.length>0;asset.updateFeed(state.spread>0?0:(state.time/PERIOD)%1);
 }
 const finite=v=>typeof v==='number'&&Number.isFinite(v);const clone=x=>JSON.parse(JSON.stringify(x));
 function invalidateSelection(){if(boxHelper){scene.remove(boxHelper);boxHelper.geometry.dispose();boxHelper.material.dispose();boxHelper=null;}if(state.selected){boxHelper=new T.Box3Helper(new T.Box3(),0xd6b77a);boxHelper.material.depthTest=false;boxHelper.material.transparent=true;boxHelper.material.opacity=.55;scene.add(boxHelper);}}
 function applyVisibility(){for(const p of asset.parts)p.visible=!state.hidden.includes(p.name)&&(!state.solo||state.solo===p.name);if(boxHelper&&state.selected)boxHelper.visible=asset.parts.find(g=>g.name===state.selected).visible;}
 function select(id){if(id!==null&&!asset.parts.some(p=>p.name===id))throw Error('未知部件');state.selected=id;invalidateSelection();sync();}
 function setSpread(v){if(!finite(v)||v<0||v>1)throw Error('展开值无效');state.spread=v;if(v>0)state.playing=false;asset.setSpread(v);updateFx();sync();}
 function setMode(m){if(!['surface','color','roughness','normal','wire'].includes(m))throw Error('模式无效');state.mode=m;if(m!=='surface')state.comparison=false;surfaces.setMode(asset.root,m);sync();}
 function setLight(name){const cfg={studio:[3,1.3,2.2,.65,.70],neutral:[2.3,1.8,.6,.85,.5],grazing:[3.5,.4,1.7,.35,.6]}[name];if(!cfg)throw Error('灯光无效');state.light=name;[key.intensity,fill.intensity,rim.intensity,ambient.intensity,scene.environmentIntensity]=cfg;key.position.set(...(name==='grazing'?[-4,2,5]:[-1,7,5]));sync();}
 function bounds(part){const box=new T.Box3();if(part){box.setFromObject(part);}else for(const p of asset.parts)if(p.visible)box.union(new T.Box3().setFromObject(p));if(box.isEmpty())box.setFromCenterAndSize(V(0,1,0),V(9,3,3));return box;}
 function view(name='hero',instant=false){state.orbit=false;controls.autoRotate=false;const dirs={hero:V(5,3.1,10),side:V(0,.15,10),rear:V(-10,2.2,4),top:V(0,10,.02),detail:V(.4,2,5)};let part=null;if(name==='detail')part=asset.parts.find(p=>p.name===(state.selected||'receiver'));const b=bounds(part),size=b.getSize(V(0,0,0)),target=b.getCenter(V(0,0,0));const direction=(dirs[name]||dirs.hero).normalize();const fov=T.MathUtils.degToRad(camera.fov),hFov=2*Math.atan(Math.tan(fov/2)*camera.aspect);const distance=Math.max(size.x/(2*Math.tan(hFov/2)),size.y/(2*Math.tan(fov/2)),size.z/(2*Math.tan(hFov/2)))*1.26;const position=target.clone().addScaledVector(direction,distance);
 if(instant){tween=null;controls.enableDamping=false;camera.position.copy(position);controls.target.copy(target);controls.update();controls.enableDamping=true;}else tween={from:camera.position.clone(),to:position,fromTarget:controls.target.clone(),toTarget:target,start:performance.now()};sync();}
 function sync(){const chosen=asset.parts.find(p=>p.name===state.selected);$('selected-label').textContent=chosen?chosen.userData.label:'完整 Aircraft 外观';$('selected-en').textContent=chosen?chosen.userData.en:'COMPLETE EXTERIOR';$('spread').value=state.spread;$('spread-out').textContent=Math.round(state.spread*100)+'%';$('play').textContent=state.playing?'暂停演示':'播放演示';$('play').setAttribute('aria-pressed',state.playing);$('play').disabled=state.spread>0;$('solo').disabled=!chosen;$('hide').disabled=!chosen;$('solo').classList.toggle('active',!!state.solo);$('compare').classList.toggle('active',state.comparison);$('ab-labels').hidden=!state.comparison;document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===state.mode));document.querySelectorAll('[data-light]').forEach(b=>b.classList.toggle('active',b.dataset.light===state.light));document.querySelectorAll('[data-part]').forEach(b=>{b.classList.toggle('active',b.dataset.part===state.selected);b.classList.toggle('muted',state.hidden.includes(b.dataset.part));});for(const k in surfaces.values){$(k).value=surfaces.values[k];$(k+'-out').value=surfaces.values[k].toFixed(2);} $('orbit').classList.toggle('active',state.orbit);}
 function toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2800);}
 function snapshot(){return {schema:VERSION,state:{...clone(state),playing:false},materials:clone(surfaces.values)};}
 function restore(s){if(!s||s.schema!==VERSION||!s.state||!s.materials)throw Error('该记录不属于 R01 规则');const n=clone(s.state);if(Object.keys(n).sort().join()!==Object.keys(state).sort().join())throw Error('状态字段不一致');const ids=asset.parts.map(p=>p.name);for(const id of [n.selected,n.solo])if(id!==null&&!ids.includes(id))throw Error('部件记录无效');if(!Array.isArray(n.hidden)||n.hidden.some(x=>!ids.includes(x))||new Set(n.hidden).size!==n.hidden.length)throw Error('隐藏列表无效');if(!finite(n.spread)||n.spread<0||n.spread>1||!finite(n.time)||n.time<0||n.time>DURATION||![.25,.5,1].includes(n.speed))throw Error('进度记录无效');if(!['surface','color','roughness','normal','wire'].includes(n.mode)||!['studio','neutral','grazing'].includes(n.light)||typeof n.comparison!=='boolean'||typeof n.orbit!=='boolean'||typeof n.playing!=='boolean')throw Error('模式记录无效');surfaces.apply(s.materials);Object.assign(state,n,{playing:false,orbit:false});controls.autoRotate=false;tween=null;asset.setSpread(state.spread);setMode(state.mode);setLight(state.light);applyVisibility();invalidateSelection();updateFx();sync();}
 function geomHash(){let h=2166136261;asset.root.traverse(o=>{if(o.isMesh){for(const k of ['position','normal']){const a=o.geometry.attributes[k]?.array;if(a)for(let i=0;i<a.length;i++){h^=(Math.round(a[i]*1000000)|0);h=Math.imul(h,16777619);}}}});return (h>>>0).toString(16);}
 const baselineHash=geomHash();
 $('tree').innerHTML=asset.parts.map((p,i)=>`<button data-part="${p.name}"><span class="part-number">${String(i+1).padStart(2,'0')}</span><span>${p.userData.label}<small>${p.userData.en}</small></span><i>›</i></button>`).join('');
 document.querySelectorAll('[data-part]').forEach(b=>b.onclick=()=>select(b.dataset.part));$('solo').onclick=()=>{state.solo=state.solo?null:state.selected;applyVisibility();view(state.solo?'detail':'hero');sync();};$('hide').onclick=()=>{const id=state.selected;if(!id)return;state.hidden=state.hidden.includes(id)?state.hidden.filter(x=>x!==id):[...state.hidden,id];applyVisibility();sync();};$('show-all').onclick=()=>{state.hidden=[];state.solo=null;select(null);applyVisibility();view('hero');};
 $('spread').oninput=e=>setSpread(Number(e.target.value));$('unfold').onclick=()=>{setSpread(state.spread>.5?0:1);view('hero');};
 for(const k in surfaces.values)$(k).oninput=e=>{surfaces.apply({...surfaces.values,[k]:Number(e.target.value)});sync();};
 $('material-reset').onclick=()=>{surfaces.apply({roughness:.5,wear:.24,oil:.2,detail:.55});sync();};
 document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{const v={service:{roughness:.5,wear:.24,oil:.2,detail:.55},dry:{roughness:.8,wear:.15,oil:.03,detail:.7},oiled:{roughness:.36,wear:.26,oil:.68,detail:.5}}[b.dataset.preset];surfaces.apply(v);sync();});
 document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));document.querySelectorAll('[data-light]').forEach(b=>b.onclick=()=>setLight(b.dataset.light));document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>view(b.dataset.view));
 $('compare').onclick=()=>{setMode('surface');state.comparison=!state.comparison;sync();};$('orbit').onclick=()=>{tween=null;state.orbit=!state.orbit;controls.autoRotate=state.orbit;sync();};
 $('play').onclick=()=>{if(state.spread>0)return;if(state.time>=DURATION)state.time=0;state.playing=!state.playing;sync();};$('replay').onclick=()=>{state.time=0;state.playing=false;updateFx();sync();};$('seek').oninput=e=>{state.time=Number(e.target.value);state.playing=false;updateFx();sync();};$('speed').onchange=e=>state.speed=Number(e.target.value);
 $('save').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(snapshot(),null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='Aircraft_R01_Parameters.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);toast('已保存参数，未保存网格或贴图');};$('load').onclick=()=>$('file').click();$('file').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>50000)throw Error('文件过大');restore(JSON.parse(await f.text()));toast('记录已恢复，演示保持暂停');}catch(err){toast(err.message);}e.target.value='';};
 $('info').onclick=()=>$('sources').showModal();$('close-info').onclick=()=>$('sources').close();$('sources').addEventListener('click',e=>{if(e.target===$('sources')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});
 $('mobile-parts').onclick=()=>{document.body.classList.toggle('parts-open');document.body.classList.remove('material-open');};$('mobile-material').onclick=()=>{document.body.classList.toggle('material-open');document.body.classList.remove('parts-open');};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>{document.body.classList.remove('material-open','parts-open');setTimeout(()=>view('hero',true),60);});
 const pointerStart={x:0,y:0};$('canvas').addEventListener('pointerdown',e=>{pointerStart.x=e.clientX;pointerStart.y=e.clientY;});$('canvas').addEventListener('pointerup',e=>{if(Math.hypot(e.clientX-pointerStart.x,e.clientY-pointerStart.y)>5)return;const r=$('canvas').getBoundingClientRect(),p=new T.Vector2((e.clientX-r.left)/r.width*2-1,1-(e.clientY-r.top)/r.height*2);const ray=new T.Raycaster();ray.setFromCamera(p,camera);const hit=ray.intersectObjects(asset.pickables,false).find(h=>asset.parts.find(g=>g.name===h.object.userData.part)?.visible);if(hit)select(hit.object.userData.part);});$('canvas').ondblclick=()=>view('detail');
 addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(document.activeElement.tagName)||$('sources').open)return;if(e.key.toLowerCase()==='f')view('hero');if(e.code==='Space'){e.preventDefault();$('play').click();}if(e.key==='Escape'){state.solo=null;state.hidden=[];select(null);applyVisibility();}});
 function resize(){const w=$('stage').clientWidth,h=$('stage').clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();}
 new ResizeObserver(()=>{resize();if(document.body.dataset.ready==='true'&&innerWidth<900)view('hero',true);}).observe($('stage'));resize();view('hero',true);sync();updateFx();
 const frameTimes=[];function draw(now){raf=requestAnimationFrame(draw);const dt=Math.min((now-last)/1000,.05);last=now;if(document.hidden)return;
 if(state.playing){state.time=Math.min(DURATION,state.time+dt*state.speed);if(state.time===DURATION){state.playing=false;sync();}updateFx();}
 if(tween){const q=Math.min((now-tween.start)/450,1),s=1-(1-q)**3;camera.position.lerpVectors(tween.from,tween.to,s);controls.target.lerpVectors(tween.fromTarget,tween.toTarget,s);if(q===1)tween=null;}
 controls.update(dt);if(boxHelper&&state.selected)boxHelper.box.copy(new T.Box3().setFromObject(asset.parts.find(g=>g.name===state.selected)));
 const w=$('stage').clientWidth,h=$('stage').clientHeight;renderer.setViewport(0,0,w,h);
 if(state.comparison){renderer.setScissorTest(true);renderer.setScissor(0,0,w/2,h);surfaces.setLayer(false);renderer.render(scene,camera);renderer.setScissor(w/2,0,w/2,h);surfaces.setLayer(true);renderer.render(scene,camera);renderer.setScissorTest(false);}else{surfaces.setLayer(true);renderer.render(scene,camera);}
 ticks++;frameTimes.push(now);while(frameTimes[0]<now-1000)frameTimes.shift();if(now-lastUI>180){$('fps').textContent=String(frameTimes.length);$('clock').textContent=state.time.toFixed(1)+' / 12.0 s';$('seek').value=state.time;$('event-count').textContent=String(Math.floor(state.time/PERIOD+1e-8)).padStart(3,'0');$('tracer-count').textContent=String(Math.floor(state.time/PERIOD/5+1e-8)).padStart(2,'0');lastUI=now;}
 }
 $('tris').textContent=Math.round(stats.triangles/1000)+'k';$('loading').hidden=true;document.body.dataset.ready='true';
 window.WM={version:VERSION,get ready(){return true;},get frames(){return ticks;},state:()=>clone(state),snapshot,restore,setSpread,setMode,setLight,select,view,materials:()=>clone(surfaces.values),setMaterials:v=>{surfaces.apply(v);sync();},seek:t=>{if(!finite(t)||t<0||t>DURATION)throw Error('无效时间');state.time=t;state.playing=false;updateFx();sync();},play:()=>{if(!state.spread){state.playing=true;sync();}},pause:()=>{state.playing=false;sync();},audit:()=>({version:VERSION,generated:true,referenceMeshLoads:0,imageTextureLoads:0,retainedMeshFiles:0,parts:asset.parts.map(p=>p.name),stats,geometryUnchanged:geomHash()===baselineHash,rootIdentity:asset.root.rotation.toArray().slice(0,3).every(x=>x===0)&&asset.root.position.length()===0,upAxis:camera.up.toArray(),restRestored:state.spread===0&&asset.parts.every(p=>p.position.distanceTo(p.userData.rest)<1e-12),events:events(state.time),activeCases:cases.count,capacity:CAPACITY,errors:[...errors],renderer:{calls:renderer.info.render.calls,triangles:renderer.info.render.triangles,geometries:renderer.info.memory.geometries},productionReady:false}),camera:()=>({position:camera.position.toArray(),target:controls.target.toArray()}),reset:()=>{state.time=0;state.hidden=[];state.solo=null;state.playing=false;setSpread(0);select(null);applyVisibility();setMode('surface');view('hero',true);updateFx();}};
 requestAnimationFrame(draw);
 }catch(e){reportError(e);}
})();
