import test from 'node:test';
import assert from 'node:assert/strict';
import { PARAMS, createSession, textureEncoding, decodeTextureSample, normalConventionY } from '../../src/mechanical-product-forge/knowledge-distillation/material-session.mjs';
import { R019_DEPENDENCIES, dependencyGate } from '../../src/mechanical-product-forge/knowledge-distillation/r019-panel-bridge.mjs';
const lock = () => Object.fromEntries(['aircraft', 'b24'].map((p, i) => [p, { revision: 'SYNTHETIC-TEST-ONLY', geometrySha256: `${i}`.repeat(64), uvSha256: 'a'.repeat(64), nodeGraphSha256: 'b'.repeat(64) }]));
const verified = () => R019_DEPENDENCIES.map(path => ({ path, available: true, expectedSha256: 'a'.repeat(64), actualSha256: 'a'.repeat(64) }));
test('R019 control IDs and values retained from indexed HTML', () => assert.deepEqual(Object.fromEntries(Object.entries(PARAMS).map(([k, v]) => [k, v.default])), { wear: .32, oil: .28, oxidation: .12, roughness: .5, detail: .68 }));
test('aircraft edits do not leak into B24', () => { const s = createSession(lock()); s.set('wear', .9); assert.equal(s.read('b24').wear, .32); });
test('B24 edits do not leak into aircraft', () => { const s = createSession(lock()); s.select('b24'); s.set('oil', .9); assert.equal(s.read('aircraft').oil, .28); });
test('reset restores session starting state for active project only', () => { const s = createSession(lock()); s.set('wear', .9); s.select('b24'); s.set('wear', .8); s.reset(); assert.equal(s.read().wear, .32); assert.equal(s.read('aircraft').wear, .9); });
test('runtime initial values take precedence over HTML defaults', () => { const b = createSession(lock()).snapshot().projects; b.b24.wear = .6; const s = createSession(lock(), { initial: b }); s.select('b24'); s.set('wear', .9); s.reset(); assert.equal(s.read().wear, .6); });
for (const value of [-1, 1.01, NaN, Infinity, -Infinity, '0.4', null, {}, []]) test(`invalid value ${String(value)} rejected without mutation`, () => { const s = createSession(lock()); const before = s.snapshot(); assert.throws(() => s.set('wear', value)); assert.deepEqual(s.snapshot(), before); });
test('unknown parameter cannot write geometry', () => { const s = createSession(lock()); assert.throws(() => s.set('vertices', .5)); });
test('unknown project rejected', () => assert.throws(() => createSession(lock()).select('other')));
test('empty source identity rejected', () => assert.throws(() => createSession({})));
test('read returns independent data', () => { const s = createSession(lock()); const v = s.read(); v.wear = .9; assert.equal(s.read().wear, .32); });
test('snapshot restores both project states', () => { const s = createSession(lock()); s.set('wear', .7); const v = s.snapshot(); s.set('wear', .1); s.restore(v); assert.equal(s.read().wear, .7); });
test('source mismatch refuses old snapshot', () => { const s = createSession(lock()); const v = s.snapshot(); v.sourceLock.aircraft.uvSha256 = 'c'.repeat(64); assert.throws(() => s.restore(v)); });
test('invalid second project makes restore atomic', () => { const s = createSession(lock()); const before = s.snapshot(); const v = s.snapshot(); v.projects.aircraft.wear = .9; v.projects.b24.oil = NaN; assert.throws(() => s.restore(v)); assert.deepEqual(s.snapshot(), before); });
test('schema mismatch rejected', () => { const s = createSession(lock()); const v = s.snapshot(); v.schema = 'other'; assert.throws(() => s.restore(v)); });
test('additional hidden field rejected', () => { const s = createSession(lock()); const v = s.snapshot(); v.projects.aircraft.extra = 1; assert.throws(() => s.restore(v)); });
test('historical read-only enforced on set/reset/import', () => { const s = createSession(lock(), { lockedProjects: ['b24'] }); assert.throws(() => s.set('wear', .8, 'b24')); assert.throws(() => s.reset('b24')); const v = s.snapshot(); v.projects.b24.wear = .8; assert.throws(() => s.restore(v)); });
for (const role of ['normalTexture','roughnessTexture','metallicTexture','occlusionTexture','heightTexture']) test(`${role} preserves data sample`, () => { assert.equal(textureEncoding(role), 'data'); assert.equal(decodeTextureSample(role, .5), .5); });
for (const role of ['baseColorTexture','emissiveTexture']) test(`${role} decodes color sample`, () => assert.ok(Math.abs(decodeTextureSample(role, .5) - .21404114048223255) < 1e-12));
test('unknown texture role is not guessed', () => assert.throws(() => textureEncoding('unknown')));
test('color endpoints retained', () => { assert.equal(decodeTextureSample('baseColorTexture', 0), 0); assert.equal(decodeTextureSample('baseColorTexture', 1), 1); });
test('normal convention changes vector Y only', () => { assert.equal(normalConventionY(.4,'opengl'), .4); assert.equal(normalConventionY(.4,'directx'), -.4); assert.throws(() => normalConventionY(.4,'unknown')); });
test('source has exactly ten direct dependencies', () => assert.equal(R019_DEPENDENCIES.length, 10));
test('no missing data fallback to previous revision', () => { const g = dependencyGate([]); assert.equal(g.ready, false); assert.equal(g.blocked, 10); });
test('all independently verified dependency identities allow a candidate', () => assert.equal(dependencyGate(verified()).ready, true));
for (const kind of ['unavailable', 'unverified_source', 'not_hashed', 'hash_mismatch', 'duplicate']) test(`dependency ${kind} blocks readiness`, () => { const v = verified(); if (kind === 'unavailable') v[0].available = false; if (kind === 'unverified_source') v[0].expectedSha256 = null; if (kind === 'not_hashed') v[0].actualSha256 = null; if (kind === 'hash_mismatch') v[0].actualSha256 = 'c'.repeat(64); if (kind === 'duplicate') v.push(v[0]); const g = dependencyGate(v); assert.equal(g.ready, false); assert.equal(g.items[0].reason, kind); });
