const state={lang:'zh',kb:null,sources:null};
const $=(s)=>document.querySelector(s);
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const text=(obj,base)=>state.lang==='zh'?(obj[base+'Zh']??obj.zh??''):(obj[base+'En']??obj.en??'');
function renderSummary(){const k=state.kb;$('#summary').innerHTML=[['42-73257','Serial'],['487','Aircraft No.'],[k.assets.length,'Evidence cards'],[state.sources.sources.length,'Sources'],[k.peopleLeads.length,'People leads']].map(([n,l])=>`<div class="stat"><strong>${esc(n)}</strong><span>${esc(l)}</span></div>`).join('')}
function renderMeaning(){const m=state.kb.nameMeaning;$('#meaning-lead').innerHTML=`<h3>${state.lang==='zh'?'资料库采用的简短解释':'Approved short explanation'}</h3><p>${esc(state.lang==='zh'?m.approvedShortExplanationZh:m.approvedShortExplanationEn)}</p><p class="section-note">${esc(state.lang==='zh'?m.doNotStateAsFactZh:m.doNotStateAsFactEn)}</p>`;$('#meaning-cards').innerHTML=m.interpretations.map(x=>`<article class="card"><div class="card-body"><div class="meta"><span class="tag grade">${esc(x.evidenceClass)}</span>${x.sourceIds.map(s=>`<span class="tag">${esc(s)}</span>`).join('')}</div><h3>${esc(state.lang==='zh'?x.titleZh:x.titleEn)}</h3><p>${esc(state.lang==='zh'?x.claimZh:x.claimEn)}</p></div></article>`).join('')}
function renderFacts(){const f=state.kb.lockedVisualFacts[state.lang];$('#visual-facts').innerHTML=f.map(x=>`<li>${esc(x)}</li>`).join('')}
function imageFor(a){return a.imagePath||a.imageUrl||''}
function renderAssets(){const q=$('#search').value.trim().toLowerCase(),grade=$('#grade-filter').value;const filtered=state.kb.assets.filter(a=>(grade==='all'||a.evidenceClass===grade)&&(!q||JSON.stringify(a).toLowerCase().includes(q)));$('#asset-cards').innerHTML=filtered.map(a=>{const img=imageFor(a);const source=a.sourcePage&&a.sourcePage!=='user-supplied'?`<a class="source-link" target="_blank" rel="noopener" href="${esc(a.sourcePage)}">${state.lang==='zh'?'打开来源页':'Open source page'}</a>`:'<span class="source-link">Local original</span>';return `<article class="card">${img?`<img loading="lazy" src="${esc(img)}" alt="${esc(state.lang==='zh'?a.titleZh:a.titleEn)}" onerror="this.outerHTML='<div class=&quot;image-fallback&quot;>External preview unavailable</div>'">`:'<div class="image-fallback">No preview</div>'}<div class="card-body"><div class="meta"><span class="tag grade">${esc(a.evidenceClass)}</span><span class="tag">${esc(a.id)}</span><span class="tag">${esc(a.side)}</span>${(a.sourceIds||[]).map(s=>`<span class="tag">${esc(s)}</span>`).join('')}</div><h3>${esc(state.lang==='zh'?a.titleZh:a.titleEn)}</h3><div class="title-en">${esc(state.lang==='zh'?a.titleEn:a.titleZh)}</div><ul>${(state.lang==='zh'?a.notes:a.notesEn).map(n=>`<li>${esc(n)}</li>`).join('')}</ul>${source}</div></article>`}).join('')||'<article class="panel">No matching records.</article>'}
function renderFlight(){const f=state.kb.finalFlight;$('#final-flight').innerHTML=`<p>${esc(state.lang==='zh'?f.summaryZh:f.summaryEn)}</p><p><strong>${esc(f.macr)}</strong></p><p class="section-note">${esc(state.lang==='zh'?f.verificationStatusZh:f.verificationStatusEn)}</p><div class="source-list">${f.crew.map(c=>`<div class="person"><strong>${esc(c.name)}</strong><br><span class="section-note">${esc(state.lang==='zh'?c.roleZh:c.roleEn)}</span></div>`).join('')}</div>`}
function renderPeople(){const p=state.kb.peopleLeads;$('#people-leads').innerHTML=p.map(x=>`<div class="person"><strong>${esc(x.name)}</strong><p>${esc(state.lang==='zh'?x.relationZh:x.relationEn)}</p><p class="section-note">${esc(state.lang==='zh'?x.statusZh:x.statusEn)}</p></div>`).join('')}
function renderSources(){const q=$('#search').value.trim().toLowerCase();const list=state.sources.sources.filter(s=>!q||JSON.stringify(s).toLowerCase().includes(q));$('#source-list').innerHTML=list.map(s=>`<article class="source-item"><div class="source-grid"><div><span class="source-id">${esc(s.id)}</span><br><span class="tag grade">${esc(s.evidenceClass)}</span></div><div><strong>${esc(state.lang==='zh'?s.titleZh:s.titleEn)}</strong><div class="source-type">${esc(s.sourceType)} · ${esc(s.organization)}</div></div><div><p>${esc(state.lang==='zh'?s.useZh:s.useEn)}</p>${s.pageUrl?`<a target="_blank" rel="noopener" href="${esc(s.pageUrl)}">${esc(s.pageUrl)}</a>`:'<span class="section-note">Local source</span>'}${(s.directMediaUrls||[]).map(u=>`<br><a target="_blank" rel="noopener" href="${esc(u)}">Direct media</a>`).join('')}</div></div></article>`).join('')}
function renderLists(){const k=state.kb;$('#open-questions').innerHTML=k.openQuestions[state.lang].map(x=>`<li>${esc(x)}</li>`).join('');$('#livery-bridge').innerHTML=k.liveryBridge[state.lang].map(x=>`<li>${esc(x)}</li>`).join('')}
function renderAll(){document.body.classList.toggle('lang-en',state.lang==='en');$('#show-zh').classList.toggle('active',state.lang==='zh');$('#show-en').classList.toggle('active',state.lang==='en');renderSummary();renderMeaning();renderFacts();renderAssets();renderFlight();renderPeople();renderSources();renderLists();$('#version').textContent=`VERSION ${state.kb.version} · ${state.kb.generatedDate}`}
async function start(){try{const [k,s]=await Promise.all([fetch('./data/knowledge-base.json',{cache:'no-store'}),fetch('./data/source-registry.json',{cache:'no-store'})]);if(!k.ok||!s.ok)throw new Error(`data HTTP ${k.status}/${s.status}`);state.kb=await k.json();state.sources=await s.json();renderAll()}catch(e){document.querySelector('main').innerHTML=`<article class="panel"><h2>Knowledge data unavailable</h2><pre>${esc(e.stack||e)}</pre></article>`}}
$('#show-zh').addEventListener('click',()=>{state.lang='zh';renderAll()});$('#show-en').addEventListener('click',()=>{state.lang='en';renderAll()});$('#search').addEventListener('input',()=>{renderAssets();renderSources()});$('#grade-filter').addEventListener('change',renderAssets);start();
