"""Reuse frozen W04 CSS only; write the W05 interface for the new source modules.
This is an offline build step. No old product runtime or reference mesh is evaluated.
"""
from pathlib import Path
import hashlib
BASE_SHA = '80457173c7d6a97954b65c42fd62799f0cc4e4db6fb54b17986a99a13cf73c62'
HEAD = '<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Aircraft W05 · 公开材质与整枪联看</title>'
EXTRA = r'''.swatches button{border-top:4px solid var(--swatch)}.color-picker{display:flex;align-items:center;gap:9px;margin:13px 0;font:10px Consolas,monospace}.color-picker input{width:34px;height:26px;padding:0;border:0;background:transparent}.color-picker small{color:#81969e;margin-left:auto}.section h3 small{font-size:8px;color:#8a9da7;font-weight:400}.surface{scrollbar-width:thin}

.scope-buttons{margin-bottom:10px}.check-option{display:flex;gap:8px;align-items:center;font-size:10px;line-height:1.7;margin:10px 0}.check-option input{accent-color:var(--accent,#cbb58f)}
.rear-note{position:absolute;left:28px;top:145px;max-width:460px;padding:9px 13px;border:1px solid #cbb58f45;background:#19232dd9;color:#d2c1a1;border-radius:6px;font-size:10px;line-height:1.7;pointer-events:none}
.rear-note[hidden],#assembly-options[hidden]{display:none}
@media(max-width:900px){.rear-note{top:175px;left:20px;right:20px;max-width:none;font-size:9px}.parts-open .rear-note,.surface-open .rear-note{display:none}.presets button{min-height:35px}.scope-buttons button{min-height:37px}}
'''
BODY = r'''</head><body>
<header><div class="brand"><span class="mark">W</span><div><b>WEAPONS MOTHER</b><small>AIRCRAFT / B24 PRIORITY / DETAIL 05</small></div></div><span class="header-tag">局部独立生成 · 整枪尚未完成</span><div class="head-actions"><button id="info">来源与边界</button><button id="choose">载入原件做对照</button></div></header>
<div class="shell"><aside class="parts"><div class="section-head"><div><span class="overline">01 / NATIVE FEATURES</span><h2>侧板与整枪联看</h2></div><button data-close aria-label="关闭部件面板">×</button></div><div class="channels scope-buttons gap"><button data-assembly="part" class="active">独立侧板</button><button data-assembly="core" disabled>主枪联看</button><button data-assembly="with-feed" disabled>整枪与箱体</button><button data-assembly="all" disabled>原件全场景</button></div>
<p id="scope-note" class="soft"></p>
<div id="assembly-options" hidden><label class="check-option"><input id="insert-native" type="checkbox" checked>换入独立生成侧板</label><label class="check-option"><input id="context-trial" type="checkbox">整枪统一材质试涂</label><p class="soft">试涂用于观察参数范围。原件尚未完成真实表面分区，默认保持中性。</p></div>
<div class="feature-count">侧板主体 + 5 个可见头部</div><div id="features" class="features gap"></div><div class="row gap"><button id="whole">显示完整侧板</button><button id="audit">核对数据</button></div><label class="parameter"><span>展示展开 <output id="spread-value">0%</output></span><input id="spread" type="range" min="0" max="1" step=".01" value="0" aria-label="侧板外观分组展开"></label><p class="soft">展开仅用于观察外观分组。切换原件对照时自动恢复，保持同一姿态。</p><div class="callout"><span class="status-label">FIRST INDEPENDENT PART</span>已生成侧板保持 W04 形态。整枪联看使用你本地的原件；其余部件尚未独立重建。螺杆、螺纹及实物内侧不补猜。</div><div class="section"><h3>可选参照</h3><p class="soft">无需载入文件即可看独立生成件。选择原始 Aircraft GLB 后，可同页联看主枪、供弹外观和大型箱体，并比较原件侧板。文件留在本机。</p><button id="choose-panel">选择 Aircraft 原件</button><div class="row gap"><button id="release" disabled>释放临时原件</button></div><p id="ref-count" class="soft">无参考网格依赖</p></div></aside>
<main class="stage-wrap"><div id="stage"><canvas id="viewport" aria-label="独立生成侧板和原件对照"></canvas><div class="title"><span class="overline">AIRCRAFT AN/M2 / SIDEPLATE STUDY</span><h1>让形状经得起对照。</h1><p>W05 · B24 优先 · 形态保留，材质扩展</p></div><div class="scope-chip"><b id="source-status">正在生成</b></div><div id="rear-note" class="rear-note" hidden>背面仍是开放的外观数据，内侧与螺杆未重建。请用整枪联看核对遮挡关系。</div><div class="tools"><button id="orbit">↻ 环绕</button></div><div id="ab" hidden><span>A · 原件侧板</span><span>B · 独立生成</span><div id="divider"></div></div><div id="split-control" hidden><input id="split" type="range" min="5" max="95" value="50" aria-label="对照分界位置"></div><div class="caption"><strong id="caption">B · 独立规则生成侧板</strong><small id="feature-note">板件主体及五个可见头部</small></div><div class="dock"><button data-view="oblique">整体斜视</button><button data-view="front">正面</button><button data-view="reverse">背面</button><button data-view="top">俯视</button><button data-view="edge">端部</button></div><div class="mobile-bar"><button id="parts-mobile">对象与展开</button><button id="surface-mobile">对照与检查</button></div><div id="error" hidden role="alert"></div></div><div class="footer"><span>拖动旋转 · 滚轮缩放 · 双击正面 · F 复位</span><span>已呈现 <b id="frames">0</b> 帧 · <b id="triangle-count">0</b> 三角形</span></div></main>
<aside class="surface"><div class="section-head"><div><span class="overline">02 / FIXED-VIEW COMPARISON</span><h2>材质与形态对照</h2></div><button data-close aria-label="关闭对照面板">×</button></div><div class="channels"><button data-display="native" class="active">B · 独立生成</button><button data-display="reference" disabled>A · 原件侧板</button><button data-display="split" disabled>A/B 同镜头</button><button data-display="overlay" disabled>双色叠合</button></div><p class="soft">对照锁定同一相机、光照、比例和材质。原件只读；生成件不读取原件顶点或 UV。</p><div class="section"><h3>做旧预设 <small>艺术候选 · 非历史定论</small></h3><div class="channels presets"><button data-preset="baseline">原版深灰</button><button data-preset="service">轻度使用</button><button data-preset="dry">干燥旧化</button><button data-preset="oily">旧金属油膜</button><button data-preset="oxidized">氧化候选</button><button data-preset="weathered">较重旧化</button></div><p class="soft">预设只改变材质，不改变几何与曝光。氧化、积灰和磨耗各自控制。</p></div>
<div class="section"><h3>表面颜色 <small>候选 · 未做历史标定</small></h3><div class="row swatches"><button data-finish="#45494b" title="中性深灰" style="--swatch:#45494b">深灰</button><button data-finish="#505455" title="较浅中性灰" style="--swatch:#505455">浅灰</button><button data-finish="#4b4945" title="低饱和暖灰" style="--swatch:#4b4945">暖灰</button></div><label class="color-picker"><input id="finish-color" type="color" value="#45494b" aria-label="表面候选颜色"><span id="color-value">#45494B</span><small>sRGB 输入</small></label>
<label class="parameter"><span>基础粗糙度 <output id="roughness-value">0.52</output></span><input id="roughness" type="range" min="0" max="1" step=".01" value=".52"></label>
<label class="parameter"><span>金属度 <output id="metalness-value">0.60</output></span><input id="metalness" type="range" min="0" max="1" step=".01" value="0.6"></label>
<label class="parameter"><span>细密粗糙度 <output id="grain-value">0.35</output></span><input id="grain" type="range" min="0" max="1" step=".01" value=".35"></label>
<label class="parameter"><span>浅表起伏 <output id="relief-value">0.20</output></span><input id="relief" type="range" min="0" max="1" step=".01" value=".20"></label>

<label class="parameter"><span>磨耗露亮 <output id="wear-value">0.00</output></span><input id="wear" type="range" min="0" max="1" step=".01" value="0"></label>
<label class="parameter"><span>氧化斑驳 <output id="oxidation-value">0.00</output></span><input id="oxidation" type="range" min="0" max="1" step=".01" value="0"></label>
<label class="parameter"><span>积灰覆盖 <output id="dust-value">0.00</output></span><input id="dust" type="range" min="0" max="1" step=".01" value="0"></label>
<label class="parameter"><span>定向细划痕 <output id="scratches-value">0.00</output></span><input id="scratches" type="range" min="0" max="1" step=".01" value="0"></label>
<label class="parameter"><span>薄膜候选 <output id="film-value">0.00</output></span><input id="film" type="range" min="0" max="1" step=".01" value="0"></label>
<p class="soft">颜色与粗糙度分开。浅表起伏不改轮廓，图案固定在部件原始坐标中。薄膜默认关闭，不自动增加锈蚀或磨白边缘。</p><button id="reset-surface">恢复本轮材质初值</button></div>
<div class="section"><h3>外观与数据通道</h3><div class="channels"><button data-channel="pbr" class="active">程序化 PBR</button><button data-channel="neutral">中性形状</button><button data-channel="basecolor">底色</button><button data-channel="roughness">粗糙度</button><button data-channel="metalness">金属度</button><button data-channel="normal">法线</button><button data-channel="facing">面向检查</button><button data-channel="wire">三角网格</button></div><p class="soft">面向检查：绿色为正面，红色为背面。开放表面沿原件使用双面观察；面向颜色单独检查，避免把能看见当成法线正确。</p></div>
<div class="section"><h3>中性照明</h3><div class="row"><button data-light="neutral" class="active">中性</button><button data-light="grazing">掠射</button><button data-light="studio">柔光</button></div><p class="soft">各灯使用中性颜色，曝光固定。不同光照下的色差仍须审阅。</p></div>
<div class="section"><h3>当前需要看清</h3><p class="soft">圆角、长开口、长短凹面、前端收窄、厚度变化，以及不同高度和方向的头部。</p><div class="boundary-note">延续W04：两枚圆头面向已修正，未添加无依据的背板。此版几何字节保持不变；内侧、螺杆和实物厚度仍待核实。</div></div><div class="section"><h3>记录可见差异</h3><textarea id="note" placeholder="哪一侧、哪一处形状还需要修正？" aria-label="对照笔记"></textarea><div class="row gap"><button id="export">保存材质与笔记</button><button id="import-note">载入记录</button></div></div></aside></div>
<input id="note-file" type="file" accept=".json,application/json" hidden><input id="file" type="file" accept=".glb,model/gltf-binary" hidden>
<dialog id="info-dialog"><div class="section-head"><span class="overline">PROVENANCE / W05</span><button id="close-info" aria-label="关闭来源说明">×</button></div><h2>独立规则与原件分开。</h2><p>本页打开时，即从可读的轮廓、分层、圆弧和头部参数生成一个侧板外观。源文件尚未选择时，生成件已经存在；选择后可临时读取完整原件作整枪联看，或只取对象25作侧板对照。独立侧板的规则不依赖这次读取。</p><p>依据为你上传的 Aircraft 原件中作者标记 sideplate_16 的可见数字外观。六个连通表面组只是本次数字样本的分组，不等于实物拆装单元。比例均以此侧板的外观跨度归一化，没有制造尺寸、配合公差、螺纹或功能性内部机构。</p><p>本轮扩展了金属度、磨耗、氧化、积灰、划痕及六套做旧预设。细节由16个标签派生的频带计算，采用像素足迹过滤的有限近似。无需图片，但逐像素计算仍有成本；没有宣称比 Blender 更快或已准确重现战时涂层。B17 照片不用于本轮着色。薄膜效果只是候选，未知化学成分保持未知。</p><p>长短凹面和前端曲线采用独立数学近似；曲面细分可调整，参数不随原网格三角数量增长。侧板继续沿用W04开放外表面，材质没有透明度。长孔能透过，背面缺少内侧体积；外露头部没有新增杆身。不能把这些当作已完成的实体背面。当前是局部候选，不能称为精确逐顶点复制，也没有完成机匣主体和整枪。</p><p>参照 GLB 只在浏览器内存中临时读取，不上传、不缓存、不内嵌在页面中。生成代码不包含源顶点、索引或 UV 表。W02 和更早的归档原样保留。</p><p>来源元数据：Misja van Laatum，AN/M2 Browning .50 cal aircraft machine gun，CC-BY-4.0。本件的拟合描述依据该参照制作，保留署名与改变说明；模型作者资料不代替历史准确性证明。通用 Three.js r170 许可证随 HTML 保存。</p></dialog><div id="notice" role="status"></div>
__RUNTIME__
</body></html>'''
def write(root):
    root=Path(root);data=(root/'frame-baseline.html').read_bytes()
    if hashlib.sha256(data).hexdigest()!=BASE_SHA:raise ValueError('Frozen CSS baseline changed')
    css=data.decode().split('<style>',1)[1].split('</style>',1)[0]
    (root/'index.template.html').write_text(HEAD+'<style>'+css+EXTRA+'</style>'+BODY,encoding='utf-8')
