import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {pathToFileURL,fileURLToPath} from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url));
const vendor=process.env.THREE_MODULE||path.join(root,'../vendor/three.module.js');
const T=await import(pathToFileURL(vendor));
const text=fs.readFileSync(path.join(root,'sideplate.js'),'utf8');
const R=new Function(text+'\nreturn SideplateRecipe;')();
const make=(quality=1)=>R.build(T,{quality});
const hash=m=>m.features.map(f=>[...f.geometry.attributes.position.array].reduce((s,x)=>s+x,0));
test('six visible source-corresponding exterior groups',()=>{const m=make();assert.equal(m.features.length,6);m.dispose();});
test('all generated positions and normals are finite',()=>{const m=make();for(const f of m.features)for(const key of ['position','normal'])assert.ok([...f.geometry.attributes[key].array].every(Number.isFinite));m.dispose();});
test('native root has no orientation compensation',()=>{const m=make();assert.deepEqual(m.root.rotation.toArray().slice(0,3),[0,0,0]);assert.deepEqual(m.root.position.toArray(),[0,0,0]);m.dispose();});
test('deterministic generation before a reference can be supplied',()=>{const a=make(),b=make();assert.deepEqual(hash(a),hash(b));a.dispose();b.dispose();});
test('sampling quality changes tessellation, not stored recipe',()=>{const a=make(.5),b=make(2);assert.notEqual(a.stats().triangles,b.stats().triangles);assert.equal(R.parameters.version,'aircraft.sideplate-appearance.w04.1');a.dispose();b.dispose();});
test('spread restores exact rest positions after repeated use',()=>{const m=make(),rest=m.features.map(f=>f.position.toArray()),before=hash(m);for(let i=0;i<1000;i++){m.setSpread(1);m.setSpread(.37);m.setSpread(0);}assert.deepEqual(m.features.map(f=>f.position.toArray()),rest);assert.deepEqual(hash(m),before);m.dispose();});
for(const invalid of [-1,2,NaN,Infinity,'0.5',null])test('invalid spread '+String(invalid),()=>{const m=make(),a=m.features.map(f=>f.position.toArray());assert.throws(()=>m.setSpread(invalid));assert.deepEqual(m.features.map(f=>f.position.toArray()),a);m.dispose();});
for(const invalid of [0,4,NaN,Infinity,'1'])test('invalid tessellation quality '+String(invalid),()=>assert.throws(()=>make(invalid)));
test('outer envelope remains ordered',()=>{for(let i=0;i<=1000;i++){const a=R.outer(i/1000);assert.ok(a[0]<=a[1]);assert.ok(a.every(Number.isFinite));}});
test('slot stays inside silhouette',()=>{for(let i=0;i<=1000;i++){const x=i/1000,o=R.outer(x),s=R.slot(x);assert.ok(s[0]>=o[0]&&s[1]<=o[1]);}});
test('relief does not exceed front/back envelope',()=>{for(let i=0;i<=1000;i++){const q=R.relief(i/1000);assert.ok(q.z>=R.parameters.back&&q.z<=R.parameters.mainFront);}});
test('two polygon heads preserve distinct elevations and orientations',()=>{const [a,b]=R.parameters.heads.filter(x=>x.kind==='polygon');assert.notEqual(a.position[2],b.position[2]);assert.notEqual(a.phase,b.phase);});
test('no reference loader or raster sampler in geometry module',()=>{for(const marker of ['ReferenceInput','GLTFLoader','TextureLoader','atob(','fetch(','localStorage','TEXCOORD_0'])assert.ok(!text.includes(marker));});

const S=new Function(fs.readFileSync(path.join(root,'surface.js'),'utf8')+';return DetailSurface;')();
test('material defaults have no unobserved film',()=>assert.equal(S.defaults.film,0));
test('material changes use explicit uniform IDs',()=>{const m=S.create(T);m.apply({roughness:.7,grain:.2,relief:.4,film:.1});assert.deepEqual(m.uniformSnapshot(),{roughness:.7,grain:.2,relief:.4,film:.1});m.dispose();});
test('invalid material state cannot partially apply',()=>{const m=S.create(T),before=m.values();assert.throws(()=>m.apply({roughness:.8,grain:NaN,relief:.2,film:0}));assert.deepEqual(m.values(),before);m.dispose();});
test('procedural sample is deterministic',()=>assert.deepEqual(S.sample([.1,.2,.3]),S.sample([.1,.2,.3])));
test('pixel footprint damps unresolved high frequencies',()=>{const a=S.sample([.13,.27,.04]);const b=S.sample([.13,.27,.04],[.1,0,0],[0,.1,0]);assert.ok(b.slice(4).reduce((s,x)=>s+x*x,0)<a.slice(4).reduce((s,x)=>s+x*x,0)*.001);});
test('material does not require a texture sampler',()=>{const text=fs.readFileSync(path.join(root,'surface.js'),'utf8');assert.ok(!text.includes('sampler2D'));assert.ok(!text.includes('TextureLoader'));});
test('display switching marks correct color-output pipeline',()=>{const m=S.create(T);m.setDisplay('color');assert.equal(m.material.toneMapped,false);m.setDisplay('metal');assert.equal(m.material.toneMapped,true);m.dispose();});
