import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {pathToFileURL,fileURLToPath} from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url));
const T=await import(pathToFileURL(process.env.THREE_MODULE||path.join(root,'../vendor/three.module.js')));
const text=fs.readFileSync(path.join(root,'sideplate.js'),'utf8');
const R=new Function(text+';return SideplateRecipe;')();
const S=new Function(fs.readFileSync(path.join(root,'surface.js'),'utf8')+';return SurfaceProgram;')();
const make=(quality=1)=>R.build(T,{quality});
function signature(m){const h=createHash('sha256');for(const f of m.features){h.update(f.name);for(const key of ['position','normal']){const a=f.geometry.attributes[key]?.array;if(a)h.update(new Uint8Array(a.buffer,a.byteOffset,a.byteLength));}const a=f.geometry.index?.array;if(a)h.update(new Uint8Array(a.buffer,a.byteOffset,a.byteLength));}return h.digest('hex');}
test('six exterior groups and retained W04 4904 triangles',()=>{const m=make();assert.equal(m.features.length,6);assert.equal(m.stats().triangles,4904);m.dispose();});
test('finite generated positions and normals',()=>{const m=make();for(const f of m.features)for(const key of ['position','normal'])assert.ok([...f.geometry.attributes[key].array].every(Number.isFinite));m.dispose();});
test('native root has no orientation patch',()=>{const m=make();assert.deepEqual(m.root.rotation.toArray().slice(0,3),[0,0,0]);assert.deepEqual(m.root.position.toArray(),[0,0,0]);m.dispose();});
test('deterministic exact runtime geometry bytes',()=>{const a=make(),b=make();assert.equal(signature(a),signature(b));a.dispose();b.dispose();});
test('sampling changes tessellation not recipe identity',()=>{const a=make(.5),b=make(2);assert.notEqual(a.stats().triangles,b.stats().triangles);assert.equal(R.parameters.version,'aircraft.sideplate-appearance.w04.1');a.dispose();b.dispose();});
test('1000 spreads restore exact poses and geometry',()=>{const m=make(),rest=m.features.map(f=>f.position.toArray()),before=signature(m);for(let i=0;i<1000;i++){m.setSpread(1);m.setSpread(.37);m.setSpread(0);}assert.deepEqual(m.features.map(f=>f.position.toArray()),rest);assert.equal(signature(m),before);m.dispose();});
for(const value of [-1,2,NaN,Infinity,'0.5',null])test('reject spread '+String(value),()=>{const m=make(),before=m.features.map(f=>f.position.toArray());assert.throws(()=>m.setSpread(value));assert.deepEqual(m.features.map(f=>f.position.toArray()),before);m.dispose();});
for(const value of [0,4,NaN,Infinity,'1'])test('reject quality '+String(value),()=>assert.throws(()=>make(value)));
test('slot stays within ordered outer envelope',()=>{for(let i=0;i<=1000;i++){const o=R.outer(i/1000),s=R.slot(i/1000);assert.ok(o.every(Number.isFinite)&&o[0]<=o[1]);assert.ok(s[0]>=o[0]&&s[1]<=o[1]);}});
test('relief stays in recorded appearance range',()=>{for(let i=0;i<=1000;i++){const q=R.relief(i/1000);assert.ok(q.z>=R.parameters.back&&q.z<=R.parameters.mainFront);}});
test('polygon heads preserve distinct elevations and orientations',()=>{const [a,b]=R.parameters.heads.filter(x=>x.kind==='polygon');assert.notEqual(a.position[2],b.position[2]);assert.notEqual(a.phase,b.phase);});
test('no source loader or raster sampler in generation',()=>{for(const marker of ['ReferenceInput','GLTFLoader','TextureLoader','atob(','fetch(','localStorage','TEXCOORD_0'])assert.ok(!text.includes(marker));});
test('new corrosion film and dust absent by default',()=>{for(const k of ['film','oxidation','dust','wear','scratches'])assert.equal(S.defaults[k],0);});
for(const [id,preset]of Object.entries(S.presets))test('preset '+id+' has complete legal values',()=>assert.deepEqual(S.validate(preset.values),preset.values));
test('nine numeric material controls',()=>assert.equal(S.numericKeys.length,9));
test('uniforms receive explicit expanded material fields',()=>{const p=S.create(T),m=p.material(new T.Matrix4()),s={uniforms:{},vertexShader:'#include <begin_vertex>',fragmentShader:'#include <color_fragment>\n#include <roughnessmap_fragment>\n#include <metalnessmap_fragment>\n#include <normal_fragment_maps>\n#include <lights_physical_fragment>\n#include <opaque_fragment>'};m.onBeforeCompile(s);p.apply({...S.defaults,metalness:.87,roughness:.31,oxidation:.2});assert.equal(s.uniforms.uW04Metalness.value,.87);assert.equal(s.uniforms.uW04Rough.value,.31);assert.equal(s.uniforms.uW04Oxidation.value,.2);p.dispose();});
test('invalid new material input is atomic',()=>{const p=S.create(T),before=p.values();assert.throws(()=>p.apply({...before,metalness:NaN}));assert.deepEqual(p.values(),before);p.dispose();});
test('unknown material fields are rejected',()=>assert.throws(()=>S.validate({...S.defaults,extra:1})));
test('colour syntax validated',()=>assert.throws(()=>S.validate({...S.defaults,color:'red'})));
test('labelled fields repeat exactly',()=>assert.deepEqual(S.evaluate('grain',[.1,.2,.3]),S.evaluate('grain',[.1,.2,.3])));
test('unresolved micro frequency attenuated',()=>{const a=S.evaluate('micro',[.13,.27,.04]),b=S.evaluate('micro',[.13,.27,.04],[.1,0,0],[0,.1,0]);assert.ok(Math.abs(b.value)<Math.abs(a.value)*.001);});
test('no raster sampler in surface program',()=>{const t=fs.readFileSync(path.join(root,'surface.js'),'utf8');assert.ok(!t.includes('sampler2D'));assert.ok(!t.includes('TextureLoader'));});
test('diagnostic channels disable tonemapping',()=>{const p=S.create(T),m=p.material(new T.Matrix4());p.setMode('metalness');assert.equal(m.toneMapped,false);p.setMode('pbr');assert.equal(m.toneMapped,true);p.dispose();});
test('forget releases temporary reference material record',()=>{const p=S.create(T),m=p.material(new T.Matrix4());assert.equal(p.count(),1);p.forget(m);assert.equal(p.count(),0);p.dispose();});
