/* Whitelisted local study view. Original material atlases never enter the release. */
const ReferenceStudy=(()=>{
 const allowed={
  '16c6d1e5edbba99d7a9b6dbff75d55b4abe5cd8974432086d576722f728a499d':{bytes:11057836,title:'立柱摇架 / 环形瞄具',author:'ChemicalFX',url:'https://sketchfab.com/3d-models/m2-browning-machine-gun-766427b4adaf49b3aa23f72c524290d7'},
  '3cb10b4c2cb6ae96656146f55e81f54a66338bcb817ed4727e4d79c38843d813':{bytes:18536776,title:'短柱枪座 / 机械照门',author:'buh',url:'https://sketchfab.com/3d-models/m2-browning-ccf212e16b6748419cea6d7b14b30b48'},
  '23273a3232a479d118e87ebeb82348498bd8f57b5559f6012a3b1476272d0fbb':{bytes:18143688,title:'精美 M2 / 材质基准',author:'emran.bayati',url:'https://sketchfab.com/3d-models/browning-m2-381c0f1939e843ceae232500e24e7231'}
 };
 async function create(T,file,environment){
  if(!Object.values(allowed).some(a=>a.bytes===file.size))throw Error('未登记的参考文件');const buffer=await file.arrayBuffer(),hash=await ReferenceInput.sha(new Uint8Array(buffer)),identity=allowed[hash];if(!identity)throw Error('参考文件身份不符');
  const dv=new DataView(buffer);if(dv.getUint32(0,true)!==0x46546c67||dv.getUint32(4,true)!==2)throw Error('GLB 头错误');let doc,bin;for(let o=12;o<buffer.byteLength;){const n=dv.getUint32(o,true),type=dv.getUint32(o+4,true);o+=8;if(o+n>buffer.byteLength)throw Error('GLB 越界');if(type===0x4e4f534a)doc=JSON.parse(new TextDecoder().decode(new Uint8Array(buffer,o,n)));if(type===0x004e4942)bin=o;o+=n;}
  const types={5126:Float32Array,5125:Uint32Array,5123:Uint16Array,5121:Uint8Array,5122:Int16Array,5120:Int8Array},width={SCALAR:1,VEC2:2,VEC3:3,VEC4:4};
  function accessor(i){const a=doc.accessors[i],v=doc.bufferViews[a.bufferView],C=types[a.componentType],w=width[a.type],size=C.BYTES_PER_ELEMENT*w,stride=v.byteStride||size,packed=new Uint8Array(a.count*size);for(let j=0;j<a.count;j++)packed.set(new Uint8Array(buffer,bin+(v.byteOffset||0)+(a.byteOffset||0)+j*stride,size),j*size);return new T.BufferAttribute(new C(packed.buffer),w,!!a.normalized);}
  const textures=[],images=await Promise.all((doc.images||[]).map(async im=>{const v=doc.bufferViews[im.bufferView],url=URL.createObjectURL(new Blob([buffer.slice(bin+(v.byteOffset||0),bin+(v.byteOffset||0)+v.byteLength)],{type:im.mimeType}));try{const t=await new T.TextureLoader().loadAsync(url);t.flipY=false;textures.push(t);return t;}finally{URL.revokeObjectURL(url);}}));
  function tex(info,color=false){if(!info)return null;const dt=doc.textures[info.index],sam=doc.samplers?.[dt.sampler]||{},t=images[dt.source].clone(),wrap={10497:T.RepeatWrapping,33071:T.ClampToEdgeWrapping,33648:T.MirroredRepeatWrapping};t.wrapS=wrap[sam.wrapS??10497];t.wrapT=wrap[sam.wrapT??10497];t.colorSpace=color?T.SRGBColorSpace:T.NoColorSpace;t.needsUpdate=true;textures.push(t);return t;}
  const materials=(doc.materials||[]).map(m=>{const p=m.pbrMetallicRoughness||{},mat=new T.MeshPhysicalMaterial({color:new T.Color().fromArray(p.baseColorFactor||[1,1,1]),metalness:p.metallicFactor??1,roughness:p.roughnessFactor??1,map:tex(p.baseColorTexture,true),metalnessMap:tex(p.metallicRoughnessTexture),roughnessMap:tex(p.metallicRoughnessTexture),normalMap:tex(m.normalTexture),aoMap:tex(m.occlusionTexture),aoMapIntensity:m.occlusionTexture?.strength??1,side:m.doubleSided?T.DoubleSide:T.FrontSide,specularIntensity:m.extensions?.KHR_materials_specular?.specularFactor??1,envMap:environment,envMapIntensity:.85});mat.opacity=p.baseColorFactor?.[3]??1;mat.transparent=m.alphaMode==='BLEND';mat.alphaTest=m.alphaMode==='MASK'?(m.alphaCutoff??.5):0;if(m.normalTexture?.scale!==undefined)mat.normalScale.setScalar(m.normalTexture.scale);return mat;});
  const nodes=doc.nodes.map(n=>{const g=new T.Group();g.name=n.name||'';if(n.matrix){g.matrix.fromArray(n.matrix);g.matrixAutoUpdate=false;}else{if(n.translation)g.position.fromArray(n.translation);if(n.rotation)g.quaternion.fromArray(n.rotation);if(n.scale)g.scale.fromArray(n.scale);}return g;}),meshes=[];
  doc.nodes.forEach((n,i)=>{if(n.mesh!==undefined)for(const p of doc.meshes[n.mesh].primitives){const geo=new T.BufferGeometry();for(const [a,key]of Object.entries({POSITION:'position',NORMAL:'normal',TANGENT:'tangent',TEXCOORD_0:'uv',TEXCOORD_1:'uv1'}))if(p.attributes[a]!==undefined)geo.setAttribute(key,accessor(p.attributes[a]));if(geo.attributes.uv&&!geo.attributes.uv1)geo.setAttribute('uv1',geo.attributes.uv.clone());if(p.indices!==undefined)geo.setIndex(accessor(p.indices));const m=new T.Mesh(geo,materials[p.material]);m.userData={sourceNode:i,originalMaterial:m.material};nodes[i].add(m);meshes.push(m);}for(const c of n.children||[])nodes[i].add(nodes[c]);});
  const root=new T.Group(),registration=new T.Group();root.add(registration);for(const i of doc.scenes[doc.scene||0].nodes)registration.add(nodes[i]);root.updateMatrixWorld(true);const matrices=nodes.map(n=>n.matrix.toArray()),parents=nodes.map(n=>n.parent),bounds=new T.Box3().setFromObject(root),size=bounds.getSize(new T.Vector3()),scale=3/Math.max(size.x,size.y,size.z),center=bounds.getCenter(new T.Vector3());registration.scale.setScalar(scale);registration.position.copy(center).multiplyScalar(-scale);root.updateMatrixWorld(true);
  return {root,meshes,materials,kind:'study',title:identity.title,identity,audit:()=>({kind:'study',identity:hash,author:identity.author,url:identity.url,sourceMatricesUnchanged:nodes.every((n,i)=>n.matrix.toArray().every((v,j)=>v===matrices[i][j])),sourceHierarchyUnchanged:nodes.every((n,i)=>n.parent===parents[i]),counts:{nodes:doc.nodes.length,meshObjects:meshes.length,animations:doc.animations?.length||0},registration:{scope:'isolated inspection only; no shared-datum parity claim',uniformScale:scale},originalMaterials:true,sourceBuffersPersisted:false}),dispose(){meshes.forEach(m=>m.geometry.dispose());materials.forEach(m=>m.dispose());textures.forEach(t=>t.dispose());root.clear();}};
 }
 return {create,allowed};
})();
