/* W07 dual-object and logic review. Historical visualization only.
   The local reference is optional and never uploaded or persisted. */
(async()=>{
  const T=THREE,$=id=>document.getElementById(id),VERSION='aircraft.anm2.w07.dual-review.1';
  const errors=[];let renderer,activeCamera,controls,refView=null,parsedRef=null,frame=0,dirty=true;
  const state={mode:'side',view:'oblique',projection:'ortho',fov:28,light:'neutral',channel:'pbr',focus:'barrel',referenceLoaded:false};
  const fail=e=>{const text=String(e?.message||e);errors.push(text);$('error').hidden=false;$('error').textContent='W07 运行检查失败：'+text;console.error(e)};
  addEventListener('error',e=>fail(e.error||e.message));addEventListener('unhandledrejection',e=>fail(e.reason));
  try{
    renderer=new T.WebGLRenderer({canvas:$('viewport'),antialias:true,alpha:false,powerPreference:'high-performance',preserveDrawingBuffer:true});
    renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.autoClear=false;
    const nativeScene=new T.Scene(),refScene=new T.Scene();
    const surface=SurfaceProgram.create(T),materials={steel:surface.make('steel'),panel:surface.make('panel'),fastener:surface.make('fastener'),edge:surface.make('edge'),barrel:surface.make('barrel'),grip:surface.make('grip'),dark:surface.make('dark')};
    const native=FullGunRecipe.build(T,materials);nativeScene.add(native.root);native.root.traverse(o=>{if(o.isMesh)o.userData.nativeMaterial=o.material});
    const nativeBox=new T.Box3().setFromObject(native.root),nativeSize=nativeBox.getSize(new T.Vector3()),nativeCenter=nativeBox.getCenter(new T.Vector3());
    const nativeAspect=[1,nativeSize.y/nativeSize.x,nativeSize.z/nativeSize.x];
    $('native-height').textContent=nativeAspect[1].toFixed(4);$('native-depth').textContent=nativeAspect[2].toFixed(4);
    const refNeutral=new T.MeshStandardMaterial({color:0x9ea8ac,metalness:.18,roughness:.63,side:T.DoubleSide});
    const refOverlay=new T.MeshStandardMaterial({color:0x56c5d9,metalness:.1,roughness:.45,transparent:true,opacity:.44,depthWrite:false,side:T.DoubleSide});
    const refNormal=new T.MeshNormalMaterial({side:T.DoubleSide});const refWire=new T.MeshBasicMaterial({color:0x75d1e0,wireframe:true,transparent:true,opacity:.7});
    function lightRig(scene){const key=new T.DirectionalLight(0xffffff,2.0);key.position.set(-1.5,3.2,4);key.castShadow=true;key.shadow.mapSize.set(1024,1024);const fill=new T.DirectionalLight(0xffffff,.85);fill.position.set(3,1,-4);const rim=new T.DirectionalLight(0xffffff,.72);rim.position.set(3.5,3,1);const hemi=new T.HemisphereLight(0xf5f7f8,0x1d2429,.66);scene.add(key,fill,rim,hemi);return{key,fill,rim,hemi};}
    const nativeLights=lightRig(nativeScene),refLights=lightRig(refScene);
    const env=new T.Scene();env.background=new T.Color(.18,.19,.20);env.add(new T.Mesh(new T.BoxGeometry(12,12,12),new T.MeshBasicMaterial({color:0x404548,side:T.BackSide})));
    for(const [p,w,h,power]of[[[0,4,4],6,3,2.1],[[-4,1.5,2],2,4,1.6],[[4,2,-2],4,2,1.85]]){const q=new T.Mesh(new T.PlaneGeometry(w,h),new T.MeshBasicMaterial({color:new T.Color(1,.98,.92).multiplyScalar(power),side:T.DoubleSide}));q.position.set(...p);q.lookAt(0,0,0);env.add(q)}
    const pm=new T.PMREMGenerator(renderer),target=pm.fromScene(env,.11,.1,30);nativeScene.environment=target.texture;refScene.environment=target.texture;nativeScene.environmentIntensity=.70;refScene.environmentIntensity=.70;pm.dispose();env.traverse(o=>{o.geometry?.dispose();o.material?.dispose()});
    const ortho=new T.OrthographicCamera(-1,1,1,-1,.001,100),persp=new T.PerspectiveCamera(28,1,.001,100);ortho.up.set(0,1,0);persp.up.set(0,1,0);activeCamera=ortho;
    function rebuildControls(){const target=controls?.target?.clone()||nativeCenter.clone(),position=activeCamera.position.clone();controls?.dispose();controls=new OrbitControls(activeCamera,$('viewport'));controls.enableDamping=true;controls.dampingFactor=.09;controls.autoRotateSpeed=.32;controls.target.copy(target);activeCamera.position.copy(position);controls.update();}
    rebuildControls();
    const dirs={oblique:new T.Vector3(1.3,.72,2.55),side:new T.Vector3(0,.035,1),reverse:new T.Vector3(0,.035,-1),top:new T.Vector3(.04,1,.02),rear:new T.Vector3(-1,.16,.72),barrel:new T.Vector3(1,.02,.02)};
    function currentAspect(){const w=$('stage').clientWidth,h=$('stage').clientHeight;return Math.max(.2,w/Math.max(1,h));}
    function fit(view=state.view){state.view=view;const direction=(dirs[view]||dirs.oblique).clone().normalize(),c=nativeCenter.clone(),s=nativeSize.clone();
      const halfMode=state.mode==='side'&&state.referenceLoaded,aspect=currentAspect()/(halfMode?2:1),span=Math.max(s.x/Math.max(.35,aspect),s.y*2.05,s.z*1.65)*1.12;
      const position=c.clone().addScaledVector(direction,span*3.2);activeCamera.position.copy(position);activeCamera.lookAt(c);controls.target.copy(c);
      if(activeCamera.isOrthographicCamera){activeCamera.left=-span*aspect/2;activeCamera.right=span*aspect/2;activeCamera.top=span/2;activeCamera.bottom=-span/2;}else{activeCamera.fov=state.fov;activeCamera.aspect=aspect;const vf=T.MathUtils.degToRad(activeCamera.fov),hf=2*Math.atan(Math.tan(vf/2)*aspect),dist=Math.max(s.y/(2*Math.tan(vf/2)),s.x/(2*Math.tan(hf/2)),s.z/(2*Math.tan(hf/2)))*1.28;activeCamera.position.copy(c).addScaledVector(direction,dist);}
      activeCamera.updateProjectionMatrix();controls.update();document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));dirty=true;
    }
    function setProjection(mode){if(!['ortho','perspective'].includes(mode))throw Error('未知相机模式');const old=activeCamera,pos=old.position.clone(),targetPoint=controls.target.clone();state.projection=mode;activeCamera=mode==='ortho'?ortho:persp;activeCamera.position.copy(pos);activeCamera.up.set(0,1,0);rebuildControls();controls.target.copy(targetPoint);$('projection').value=mode;document.querySelectorAll('[data-camera]').forEach(b=>b.classList.toggle('active',b.dataset.camera===mode));fit(state.view);}
    function setFov(v){v=Number(v);if(!Number.isFinite(v)||v<20||v>42)throw Error('视角越界');state.fov=v;persp.fov=v;persp.updateProjectionMatrix();$('fov').value=v;$('fov-out').value=v+'°';if(state.projection==='perspective')fit(state.view);dirty=true;}
    function setMode(mode){if(!['side','overlay','native','reference'].includes(mode))throw Error('未知显示方式');if((mode==='overlay'||mode==='reference')&&!state.referenceLoaded)return;state.mode=mode;document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));$('labels').hidden=mode==='overlay';$('divider').hidden=mode!=='side'||!state.referenceLoaded;if(mode==='side'){$('labels').classList.remove('single');$('labels').children[0].textContent=state.referenceLoaded?'A · 参考原件':'A · 原件待载入';$('labels').children[1].textContent='B · 独立生成 W06';}else if(mode==='native'){$('labels').hidden=false;$('labels').classList.add('single');$('labels').children[0].textContent='B · 独立生成 W06';}else if(mode==='reference'){$('labels').hidden=false;$('labels').classList.add('single');$('labels').children[0].textContent='A · 参考原件';}fit(state.view);dirty=true;}
    function setLight(name){const q={neutral:[2,.85,.72,.66,.70],grazing:[3.2,.22,.95,.28,.48],studio:[1.75,1.2,1.25,.82,.84]}[name];if(!q)throw Error('未知灯光');state.light=name;for(const L of[nativeLights,refLights]){[L.key.intensity,L.fill.intensity,L.rim.intensity,L.hemi.intensity]=q;L.key.position.set(...(name==='grazing'?[-1.5,.22,4]:[-1.5,3.2,4]));}nativeScene.environmentIntensity=refScene.environmentIntensity=q[4];document.querySelectorAll('[data-light]').forEach(b=>b.classList.toggle('active',b.dataset.light===name));dirty=true;}
    function setChannel(name){if(!['pbr','normal','wire'].includes(name))throw Error('未知通道');state.channel=name;surface.setMode('pbr');native.root.traverse(o=>{if(o.isMesh)o.material=name==='normal'?surface.normal:name==='wire'?surface.wire:o.userData.nativeMaterial});applyReferenceMaterial();document.querySelectorAll('[data-channel]').forEach(b=>b.classList.toggle('active',b.dataset.channel===name));dirty=true;}
    function applyReferenceMaterial(){if(!refView)return;const m=state.mode==='overlay'?refOverlay:state.channel==='normal'?refNormal:state.channel==='wire'?refWire:refNeutral;for(const mesh of refView.meshes)mesh.material=m;}
    function updateMetrics(measure){if(!measure)return;const sh=measure.sourceAspect[1],sd=measure.sourceAspect[2],nh=measure.nativeAspect[1],nd=measure.nativeAspect[2];const vals=$('metrics').querySelectorAll('b');vals[0].textContent='1.0000';vals[1].textContent=sh.toFixed(4);vals[2].textContent=nh.toFixed(4);vals[3].textContent=((nh/sh-1)*100).toFixed(1)+'%';vals[3].className=Math.abs(nh/sh-1)>.08?'warn':'';vals[4].textContent=sd.toFixed(4);vals[5].textContent=nd.toFixed(4);vals[6].textContent=((nd/sd-1)*100).toFixed(1)+'%';vals[6].className=Math.abs(nd/sd-1)>.08?'warn':'';}
    async function loadReference(file){$('file-note').textContent='正在核验原件身份和51项访问器…';const parsed=await ReferenceInput.read(file);if(refView){refScene.remove(refView.wrapper);refView.dispose();}
      parsedRef=parsed;refView=ReferenceView.create(T,parsed,refNeutral);refScene.add(refView.wrapper);const measure=refView.normalizeTo(nativeBox);updateMetrics(measure);state.referenceLoaded=true;applyReferenceMaterial();
      $('source-card').classList.add('loaded');$('source-card').innerHTML=`<strong>参考原件常驻成功</strong><small>${file.name}<br>28节点 · 13网格 · 51访问器 · 只读本地内存</small>`;$('file-note').textContent='原件已核验。生成规则没有读取其顶点或UV。';$('release').disabled=false;$('ref-status').textContent='REF 13';document.querySelectorAll('[data-mode="overlay"],[data-mode="reference"]').forEach(b=>b.disabled=false);setMode('side');$('callout').textContent='原件与生成件现在使用同一尺度和同一视角。先看枪管后段、供弹入口和顶部瞄具缺口。';dirty=true;}
    function releaseReference(){if(!refView)return;refScene.remove(refView.wrapper);refView.dispose();refView=null;parsedRef=null;state.referenceLoaded=false;$('source-card').classList.remove('loaded');$('source-card').innerHTML='<strong>参考对象等待载入</strong><small>选择已确认的 Aircraft GLB。文件只在浏览器本地读取，不上传、不缓存。</small>';$('file-note').textContent='原件只留在当前浏览器内存中。';$('release').disabled=true;$('ref-status').textContent='REF 0';document.querySelectorAll('[data-mode="overlay"],[data-mode="reference"]').forEach(b=>b.disabled=true);setMode('native');dirty=true;}
    const focusText={ammo:'弹药箱和容量关系要绑定具体 B24 枪位资料，当前先保留为空。',feed:'供弹入口和顶盖是下一轮外形补件重点，不能用一条弹链遮住缺口。',lock:'闭锁与定位先建立功能依赖，内部几何暂不做成虚构结构。',fire:'击发关系进入状态图，外部可见控制件仍需对应资料。',barrel:'枪管后段需要从原件和图纸同时量取，与机匣连续关系分开记录。',dispose:'弹壳与链节必须分别核对 B24 枪位的收集或排出路径。',sight:'瞄具按 B24 具体枪位确定，当前整枪顶部缺失保持可见。',mount:'枪体和 B24 安装系统分层。枪架、吊具、接口尚未加入。'};
    function focus(key,noFit=false){state.focus=key;document.querySelectorAll('[data-focus]').forEach(b=>b.classList.toggle('active',b.dataset.focus===key));$('callout').textContent=focusText[key]||'';$('callout').hidden=false;if(!noFit){if(key==='barrel')fit('barrel');else if(key==='sight'||key==='feed')fit('top');else fit('oblique');}}
    function signature(){let h=2166136261;native.root.traverse(o=>{if(o.isMesh)for(const k of['position','normal']){const a=o.geometry.attributes[k]?.array;if(a)for(let i=0;i<a.length;i++){h^=Math.round(a[i]*1e6)|0;h=Math.imul(h,16777619)}}});return(h>>>0).toString(16)}
    const baseline=signature();
    function renderScene(scene,x,w,h){renderer.setViewport(x,0,w,h);renderer.setScissor(x,0,w,h);renderer.setClearColor(0x1c2933,1);renderer.clear(true,true,true);renderer.render(scene,activeCamera);}
    function draw(){requestAnimationFrame(draw);if(document.hidden)return;controls.update();if(!dirty&&!controls.autoRotate)return;const w=$('stage').clientWidth,h=$('stage').clientHeight;renderer.setScissorTest(true);
      if(state.mode==='side'&&state.referenceLoaded){const half=Math.floor(w/2);renderScene(refScene,0,half,h);renderScene(nativeScene,half,w-half,h);}
      else if(state.mode==='reference'&&state.referenceLoaded)renderScene(refScene,0,w,h);
      else if(state.mode==='overlay'&&state.referenceLoaded){applyReferenceMaterial();renderScene(nativeScene,0,w,h);renderer.clearDepth();renderer.setViewport(0,0,w,h);renderer.setScissor(0,0,w,h);renderer.render(refScene,activeCamera);}
      else renderScene(nativeScene,0,w,h);
      renderer.setScissorTest(false);dirty=false;frame++;$('frames').textContent=frame;}
    function resize(){const w=$('stage').clientWidth,h=$('stage').clientHeight;renderer.setSize(w,h,false);fit(state.view);}
    $('choose').onclick=$('choose-panel').onclick=()=>$('file').click();$('file').onchange=async e=>{try{const f=e.target.files[0];if(f)await loadReference(f);}catch(err){fail(err);$('file-note').textContent=err.message;}finally{e.target.value='';}};$('release').onclick=releaseReference;
    document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));document.querySelectorAll('[data-camera]').forEach(b=>b.onclick=()=>setProjection(b.dataset.camera));$('projection').onchange=e=>setProjection(e.target.value);$('fov').oninput=e=>setFov(e.target.value);document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>fit(b.dataset.view));document.querySelectorAll('[data-light]').forEach(b=>b.onclick=()=>setLight(b.dataset.light));document.querySelectorAll('[data-channel]').forEach(b=>b.onclick=()=>setChannel(b.dataset.channel));document.querySelectorAll('[data-focus]').forEach(b=>b.onclick=()=>focus(b.dataset.focus));
    $('info').onclick=()=>$('info-dialog').showModal();$('close-info').onclick=()=>$('info-dialog').close();$('open-logic').onclick=()=>{document.body.classList.toggle('logic-open');document.body.classList.remove('review-open')};$('open-review').onclick=()=>{document.body.classList.toggle('review-open');document.body.classList.remove('logic-open')};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>{document.body.classList.remove('logic-open','review-open');setTimeout(()=>resize(),60)});
    new ResizeObserver(resize).observe($('stage'));setProjection('ortho');setFov(28);setMode('side');setLight('neutral');setChannel('pbr');focus('barrel',true);resize();$('native-status').textContent='NATIVE '+native.stats().meshes;$('loading').hidden=true;document.body.dataset.ready='true';requestAnimationFrame(draw);
    window.W07={ready:true,get frame(){return frame},state:()=>({...state}),loadReference,releaseReference,fit,setMode,setProjection,setFov,focus,audit:()=>({schema:VERSION,referenceLoaded:state.referenceLoaded,referenceAudit:refView?.audit()||null,nativeParts:native.stats().parts,nativeMeshes:native.stats().meshes,nativeTriangles:native.stats().triangles,nativeGeometryUnchanged:signature()===baseline,projection:state.projection,fov:state.fov,productMeshFiles:0,productRasterTextures:0,referenceEmbedded:false,functionGaps:['ammo','feed','barrel-continuity','disposal','sight','mount'],errors:[...errors],visualAcceptance:false,productionReady:false})};
  }catch(e){fail(e);$('loading').hidden=true;}
})();
