import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { VertexNormalsHelper } from 'three/addons/helpers/VertexNormalsHelper.js';
import { createB24VerticalTailRuntime } from '../../src/b24-native/vertical-tail-runtime-v001.js';

const host=document.querySelector('#canvas'),scene=new THREE.Scene();scene.background=new THREE.Color(0x071014);const camera=new THREE.PerspectiveCamera(36,1,.01,100);camera.position.set(10,5,10);const renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));host.append(renderer.domElement);const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,1.6,0);scene.add(new THREE.HemisphereLight(0xdffaff,0x142027,2.2));const key=new THREE.DirectionalLight(0xffffff,3);key.position.set(6,9,8);scene.add(key);scene.add(new THREE.GridHelper(20,20,0x24434b,0x13272d));
const runtime=createB24VerticalTailRuntime(THREE);scene.add(runtime.root);const normals=[];for(const mesh of runtime.components.values()){const helper=new VertexNormalsHelper(mesh,.08,0x65ff92);helper.visible=false;normals.push(helper);scene.add(helper)}
const source=document.querySelector('#source'),report=document.querySelector('#report');let mode='native';const refresh=()=>{const state=runtime.report();report.textContent=JSON.stringify(state,null,2);for(const mesh of runtime.components.values()){mesh.material.forEach((material,index)=>{material.wireframe=mode==='wireframe';if(mode==='object')material.color.set(mesh.userData.componentId.includes('left')?(mesh.userData.role==='rudder'?0xff784e:0x4a84ff):(mesh.userData.role==='rudder'?0xffd34e:0x56df8b));else if(mode==='surface')material.color.set(index===0?0x9b5de5:0x00bbf9);else material.color.set(mesh.userData.role==='rudder'?(index===0?0xc97738:0x8c512f):(index===0?0x4f9ca5:0x376d73))})}source.classList.toggle('show',mode==='reference'||mode==='overlay');source.style.opacity=mode==='overlay'?'.38':'1';normals.forEach(h=>h.visible=mode==='normals')};
const setIsolate=side=>{for(const mesh of runtime.components.values())mesh.visible=side==='all'||mesh.userData.side===side;refresh()};document.querySelectorAll('[data-mode]').forEach(button=>button.onclick=()=>{mode=button.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('active',x===button));refresh()});document.querySelectorAll('[data-yaw]').forEach(button=>button.onclick=()=>{document.querySelector('#yaw').value=button.dataset.yaw;runtime.setPilotYaw(button.dataset.yaw);refresh()});document.querySelector('#yaw').oninput=e=>{runtime.setPilotYaw(e.target.value);refresh()};document.querySelectorAll('[data-isolate]').forEach(button=>button.onclick=()=>{const side=button.dataset.isolate;document.querySelectorAll('[data-isolate]').forEach(x=>x.classList.toggle('active',x===button));setIsolate(side)});
const resize=()=>{const w=host.clientWidth,h=host.clientHeight;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h,false)};addEventListener('resize',resize);resize();refresh();document.body.dataset.qa='pass';document.querySelector('#qa').textContent='FUNCTIONAL CANDIDATE · APPROVALS FALSE';window.__B24_VERTICAL_TAIL__={runtime,scene,camera,renderer,controls,setMode:value=>{mode=value;refresh()},setIsolate,isolationReport:()=>Object.fromEntries([...runtime.components].map(([id,mesh])=>[id,mesh.visible])),report:()=>runtime.report()};renderer.setAnimationLoop(()=>{controls.update();renderer.render(scene,camera)});
