const fs=require('fs'),path=require('path'),assert=require('assert'),crypto=require('crypto');const{chromium}=require('C:/Users/Administrator/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const root='G:/AIRCRAFT/object-dna-mother/production/aircraft-anm2-v0.2',out=root+'/validation/w13';
(async()=>{const b=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});try{const p=await b.newPage({viewport:{width:1600,height:1100}}),errors=[],hostIssues=[];p.on('pageerror',e=>errors.push(String(e)));p.on('console',m=>{if(m.type()==='error'){const u=m.location().url;if(u==='https://raw.githack.com/favicon.ico'||u.startsWith('https://server.ethicalads.io/'))hostIssues.push({url:u,error:m.text()});else errors.push({url:u,error:m.text()});}});
let response=await p.goto(process.env.W13_URL||'file:///'+root+'/releases/w13/AIRCRAFT_ANM2_OBJECT_DNA_W13.html',{timeout:60000});if(await p.getByRole('button',{name:'Open the page',exact:true}).count())[response]=await Promise.all([p.waitForNavigation({timeout:60000}),p.getByRole('button',{name:'Open the page',exact:true}).click()]);await p.waitForFunction(()=>window.reviewReady);if(process.env.W13_URL)assert.equal(crypto.createHash('sha256').update(await response.body()).digest('hex'),JSON.parse(fs.readFileSync(root+'/releases/w13/AIRCRAFT_ANM2_OBJECT_DNA_W13.receipt.json')).sha256);
const shot=async name=>p.screenshot({path:out+'/'+(process.env.W13_URL?'PUBLIC-':'QA-')+name+'.png',fullPage:true});await shot('default');
const stats=await p.evaluate(()=>review.stats());assert(stats.finite&&stats.degenerate===0&&stats.badNormals===0&&stats.triangles<=300000);const cams=[];for(const v of ['action','oblique','rearOblique','front','back','top','side']){await p.evaluate(v=>review.setView(v),v);const c=await p.evaluate(()=>review.cameraAudit());if(['action','oblique','rearOblique'].includes(v))assert(c.nearSegment>c.farSegment*1.9);else assert(Math.abs(c.nearSegment-c.farSegment)<1e-10);assert(c.determinant>0);cams.push({view:v,...c});}
await p.evaluate(()=>review.setRegion('assembly'));const coords=await p.evaluate(()=>review.coordinateAudit());assert(coords.every(c=>c.determinant>0&&c.actual.every((x,i)=>Math.abs(x-c.expected[i])<1e-9)));const hash=async()=>crypto.createHash('sha256').update(await p.evaluate(()=>JSON.stringify(review.exportGeneratedBuffers()))).digest('hex'),before=await hash();
const clips={};for(const [clip,count]of [['single',1],['burst',10],['tracer',15],['reel',21]]){await p.evaluate(c=>{review.animation.play(c);review.animation.pause();review.animation.seek(99);},clip);const a=await p.evaluate(()=>review.animation.audit());assert.equal(a.shots,count);assert.equal(a.settled,count);assert.deepStrictEqual(a.tracers,Array.from({length:Math.floor(count/5)},(_,i)=>(i+1)*5));assert(a.cases.every(c=>c.rebounds===2&&c.contacts===3&&c.state==='sleeping'&&c.velocity.every(v=>v===0)&&c.minimumY>=a.contract.groundY-1e-6));clips[clip]=a;}
await p.evaluate(()=>{review.animation.play('tracer');review.animation.pause();review.animation.seek(1.2);});await shot('tracer');const a1=await p.evaluate(()=>review.animation.audit());await p.evaluate(()=>{review.animation.seek(2.8);review.animation.seek(1.2);});assert.deepStrictEqual(await p.evaluate(()=>review.animation.audit()),a1);
for(const t of [.36,.5,.7,.9,1.1,1.4,1.8,2.3]){await p.evaluate(t=>review.animation.seek(t),t);const a=await p.evaluate(()=>review.animation.audit());assert(a.cases.every(c=>c.minimumY>=a.contract.groundY-1e-6),'case crossed ground at '+t);}
await p.evaluate(()=>{review.setRegion('eject');review.setView('action');review.animation.seek(1.2);});await shot('eject');await p.evaluate(()=>review.animation.seek(7));await shot('eject-settled');
await p.evaluate(()=>review.setRegion('assembly'));assert.equal(await hash(),before);await p.evaluate(()=>review.setExplode(1));await shot('expanded');await p.evaluate(()=>review.setExplode(0));assert.equal(await hash(),before);
await p.locator('[data-region="caseDetail"]').click();await shot('headstamp');await p.locator('[data-region="box"]:visible').first().click();await p.evaluate(()=>review.setLid(1));await shot('box-open');await p.evaluate(()=>review.setLid(0));await p.locator('[data-region="sights"]').click();await p.locator('#sight-type').selectOption('frame');await shot('frame-sight');await p.locator('#sight-type').selectOption('ring');await p.locator('[data-region="showcase"]').click();await p.locator('#mount-type').selectOption('compact');await shot('compact-mount');await p.locator('#mount-type').selectOption('tall');
const refDir='G:/飞虎队十四航空队/各种机型/B-24_CBI/',refs=[];for(const [file,kind]of [['anm2_browning_.50_cal_aircraft_machine_gun.glb','original'],['12.7x99mm_m2_ball_still_practice_no_texture.glb','cal50'],['低模带底座m2_browning_machine_gun.glb','study'],['很小m2_browning.glb','study'],['精美browning_m2.glb','study']]){await p.evaluate(()=>window.referenceReady=false);await p.locator('#reference-file').setInputFiles(refDir+file);await p.waitForFunction(()=>window.referenceReady);const a=await p.evaluate(()=>review.referenceAudit());assert(a.sourceMatricesUnchanged&&a.sourceHierarchyUnchanged);assert.equal((await p.evaluate(()=>review.current())).referenceKind,kind);if(kind==='original'){for(const v of ['oblique','rearOblique','front','back','top','side']){await p.evaluate(v=>review.setView(v),v);const c=await p.evaluate(()=>review.cameraAudit());assert.deepStrictEqual(c.viewports[0],c.viewports[1]);await shot('paired-'+v);}await p.setViewportSize({width:390,height:844});await p.evaluate(()=>review.setView('side'));const c=await p.evaluate(()=>review.cameraAudit());assert.deepStrictEqual(c.viewports[0],c.viewports[1]);await shot('paired-mobile');await p.setViewportSize({width:1600,height:1100});}refs.push({file,...a});await shot('reference-'+refs.length);}
await p.locator('[data-region="showcase"]').click();await p.locator('[data-clip="single"]').click();await p.waitForFunction(()=>review.animation.state().shots===1);await p.locator('#pause-animation').click();const paused=await p.evaluate(()=>review.animation.state().time);await p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));assert.equal(await p.evaluate(()=>review.animation.state().time),paused);
await p.locator('#study-options summary').click();const download=p.waitForEvent('download');await p.locator('#export-dna').click();const dl=await download,packet=JSON.parse(fs.readFileSync(await dl.path()));assert(packet.presentation.animation.contract.tracerEvery===5);assert.equal(new Set(packet.objects.map(x=>x.id)).size,packet.objects.length);await p.locator('#study-options summary').click();
await p.setViewportSize({width:390,height:844});await shot('mobile');assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.locator('[data-region="caseDetail"]').click();await shot('mobile-headstamp');assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
fs.writeFileSync(out+'/'+(process.env.W13_URL?'PUBLIC-':'')+'ERRORS.json',JSON.stringify({errors,hostIssues},null,2));assert.deepStrictEqual(errors,[]);const data={passed:true,stats,objectCount:coords.length,cameras:cams,clipSummary:Object.fromEntries(Object.entries(clips).map(([k,a])=>[k,{shots:a.shots,tracers:a.tracers,settled:a.settled,allTwoBounce:true}])),groundChecksPassed:true,deterministicRewind:true,restGeometryRestored:true,referenceAudits:refs,exportVerified:true,mobileNoOverflow:true,errors,hostIssues,url:process.env.W13_URL||null,byteIdentityVerified:!!process.env.W13_URL};fs.writeFileSync(out+'/'+(process.env.W13_URL?'PUBLIC-':'')+'QA.json',JSON.stringify(data,null,2));console.log(JSON.stringify(data));}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});


