const fs=require('fs'),path=require('path'),assert=require('assert'),crypto=require('crypto'),{pathToFileURL}=require('url');
const {chromium}=require('C:/Users/Administrator/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'..'),out=path.join(root,'validation/w12');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});try{
const page=await browser.newPage({viewport:{width:1600,height:1100}}),errors=[];page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
await page.goto(process.env.W12_URL||pathToFileURL(path.join(root,'releases/w12/AIRCRAFT_ANM2_OBJECT_DNA_W12.html')).href);await page.waitForFunction(()=>window.reviewReady);
const shot=async name=>page.screenshot({path:path.join(out,(process.env.W12_URL?'PUBLIC-':'')+name+'.png'),fullPage:true});await shot('default');
const stats=await page.evaluate(()=>review.stats());console.log(JSON.stringify(stats));assert(stats.finite&&stats.triangles<=240000&&stats.meshes<=380&&stats.degenerate===0&&stats.badNormals===0);
const dna=await page.evaluate(()=>review.dnaPacket());assert.equal(dna.objects.filter(e=>e.typeOf==='cartridge-visual-template/2').length,58);assert.equal(new Set(dna.objects.map(e=>e.id)).size,dna.objects.length);
const coords=await page.evaluate(()=>review.coordinateAudit());for(const e of coords){assert(e.determinant>0);assert(e.actual.every((n,i)=>Math.abs(n-e.expected[i])<1e-10),e.id);}
const hash=()=>page.evaluate(()=>JSON.stringify(review.exportGeneratedBuffers())).then(s=>crypto.createHash('sha256').update(s).digest('hex'));const before=await hash();
await page.locator('[data-region="round"]').click();await page.evaluate(()=>review.setView('side'));await shot('round-assembled');await page.evaluate(()=>{review.setSeparation(1);review.setView('oblique');});await shot('round-separated');
await page.locator('[data-region="box"]').click();await shot('box-closed');await page.evaluate(()=>review.setLid(1));await shot('box-open');
await page.locator('[data-region="muzzle"]').click();await page.evaluate(()=>review.setView('front'));await shot('muzzle-front');await page.evaluate(()=>review.setView('oblique'));await shot('muzzle-oblique');
await page.evaluate(()=>{review.setLid(0);review.setSeparation(0);review.setRegion('assembly');review.setExplode(1);review.selectObject('W11/rear/control');});await shot('expanded');await page.evaluate(()=>{review.setExplode(0);review.selectObject('');});assert.equal(await hash(),before);
assert.equal((await page.evaluate(()=>review.dnaPosition('W11/round/01',{}))).status,'unknown-context');
const field=await page.evaluate(()=>{const a=review.surfaceAudit();return review.surfaceQuery({domainId:a.domains[0].domainId,position:[.1,.2,.3]});});await page.evaluate(()=>{review.setLight('grazing');review.setView('rearOblique');});assert.deepStrictEqual(await page.evaluate(()=>{const a=review.surfaceAudit();return review.surfaceQuery({domainId:a.domains[0].domainId,position:[.1,.2,.3]});}),field);await page.evaluate(()=>{review.setLight('studio');review.setSurfaceState('handled');review.setSurfaceState('coated');});
await page.locator('#reference-file').setInputFiles('G:/飞虎队十四航空队/各种机型/B-24_CBI/12.7x99mm_m2_ball_still_practice_no_texture.glb');await page.waitForFunction(()=>window.referenceReady);const cal50=await page.evaluate(()=>review.referenceAudit());assert(cal50.sourceMatricesUnchanged&&cal50.sourceHierarchyUnchanged);await page.evaluate(()=>review.setView('side'));await shot('cal50-compare');await page.locator('#source-all').click();await shot('cal50-complete');await page.locator('#source-all').click();
await page.evaluate(()=>window.referenceReady=false);await page.locator('#reference-file').setInputFiles(JSON.parse(fs.readFileSync(path.join(root,'CURRENT.json'))).referenceInput.localPath);await page.waitForFunction(()=>window.referenceReady);const original=await page.evaluate(()=>review.referenceAudit());assert(original.sourceMatricesUnchanged&&original.sourceHierarchyUnchanged);await page.evaluate(()=>{review.setRegion('assembly');review.setView('oblique');});await shot('original-compare');
await page.evaluate(()=>{review.setCompare(false);review.setLid(1);review.setSeparation(1);review.setExplode(1);review.setCompare(true);});const state=await page.evaluate(()=>review.current());assert(!state.lid&&!state.separation&&!state.expansion);
assert.equal((await page.evaluate(()=>review.muzzleAudit())).centerHits,0);
const baseline=await browser.newPage();await baseline.goto(pathToFileURL(path.join(root,'releases/w11/AIRCRAFT_ANM2_OBJECT_DNA_W11.html')).href);await baseline.waitForFunction(()=>window.reviewReady);
const stable=a=>a.filter(m=>!['barrel','supplyBox','supplyBelt'].includes(m.semantic)).map(m=>({name:m.name,indices:m.indices,vertices:m.vertices.map(v=>Math.round(v*1e7))}));
assert.deepStrictEqual(stable(await page.evaluate(()=>review.exportGeneratedBuffers())),stable(await baseline.evaluate(()=>review.exportGeneratedBuffers())));await baseline.close();
const dlPromise=page.waitForEvent('download');await page.locator('#export-dna').click();const dl=await dlPromise;assert.equal(JSON.parse(fs.readFileSync(await dl.path())).objects.length,dna.objects.length);
await page.setViewportSize({width:390,height:844});await page.locator('[data-region="round"]').click();await page.evaluate(()=>review.setSeparation(1));await shot('mobile-round');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
assert.deepStrictEqual(errors,[]);const result={passed:true,stats,errors,objectCount:dna.objects.length,coordinateChainVerified:coords.length,assemblyGeometryRestored:true,realReferenceLoaded:true,cal50,original,muzzleCenterOpen:true,unchangedW11Core:true,materialFieldStable:true,exportVerified:true,mobileNoOverflow:true,url:process.env.W12_URL||null};fs.writeFileSync(path.join(out,process.env.W12_URL?'PUBLIC-QA.json':'QA.json'),JSON.stringify(result,null,2));console.log('W12 QA passed');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
