import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';

const LOCK=Object.freeze({bytes:23085972,sha256:'541c3dcfb98ab590cdb1bc90d6ddcdfe80bce2a4b937f3bccefab0c7efe8be0d',scenes:1,nodes:1784,meshes:348,triangles:325358,materials:30,images:18,animations:1,animationChannels:2518});
const $=id=>document.getElementById(id);
const state={renderer:null,scene:null,camera:null,controls:null,wrapper:null,root:null,grid:null,axes:null,boxHelper:null,mixer:null,action:null,clip:null,clock:new THREE.Clock(),playing:false,speed:1,records:[],recordByObject:new Map(),selected:null,visibility:new Map(),wireframes:new Map(),raycaster:new THREE.Raycaster(),pointer:new THREE.Vector2()};

const formatBytes=n=>`${(n/1e6).toFixed(2)} MB`;
const hex=buffer=>[...new Uint8Array(buffer)].map(v=>v.toString(16).padStart(2,'0')).join('');
const esc=value=>String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function pill(el,text,kind=''){el.textContent=text;el.className=`pill${kind?` ${kind}`:''}`}
function progress(value,label,bytes){$('progress').style.width=`${Math.min(100,Math.max(0,value*100)).toFixed(1)}%`;$('progressLabel').textContent=label;if(bytes!==undefined)$('progressBytes').textContent=`${formatBytes(bytes)} / ${formatBytes(LOCK.bytes)}`}
function fail(error){const message=error instanceof Error?error.message:String(error);$('errorBox').textContent=message;$('errorBox').classList.add('show');$('loadingText').textContent='装载失败。页面已经停止，不会使用替代模型。';pill($('sourcePill'),'源文件校验失败','bad');pill($('runtimePill'),'运行时停止','bad');document.body.dataset.qa='fail';console.error(error)}

function initScene(){
  state.renderer=new THREE.WebGLRenderer({canvas:$('canvas'),antialias:true,powerPreference:'high-performance'});
  state.renderer.outputColorSpace=THREE.SRGBColorSpace;state.renderer.toneMapping=THREE.ACESFilmicToneMapping;state.renderer.toneMappingExposure=1.05;state.renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));
  state.scene=new THREE.Scene();state.scene.background=new THREE.Color(0x07100f);state.scene.fog=new THREE.FogExp2(0x07100f,.002);
  state.camera=new THREE.PerspectiveCamera(36,1,.01,10000);state.controls=new OrbitControls(state.camera,$('canvas'));state.controls.enableDamping=true;state.controls.dampingFactor=.07;state.controls.screenSpacePanning=true;state.controls.autoRotateSpeed=.7;
  state.scene.add(new THREE.HemisphereLight(0xe7f0ed,0x26322e,2.1));
  const key=new THREE.DirectionalLight(0xffebbd,3.5);key.position.set(15,24,18);state.scene.add(key);
  const fill=new THREE.DirectionalLight(0x9ed6e0,2.1);fill.position.set(-18,8,-16);state.scene.add(fill);
  const rim=new THREE.DirectionalLight(0xb7d1ff,1.4);rim.position.set(2,-10,22);state.scene.add(rim);
  state.grid=new THREE.GridHelper(120,60,0x49645f,0x243732);state.grid.material.transparent=true;state.grid.material.opacity=.38;state.scene.add(state.grid);
  state.axes=new THREE.AxesHelper(8);state.axes.visible=false;state.scene.add(state.axes);
  state.boxHelper=new THREE.BoxHelper(undefined,0xf1c96d);state.boxHelper.visible=false;state.scene.add(state.boxHelper);
  resize();addEventListener('resize',resize);$('canvas').addEventListener('dblclick',pick);pill($('runtimePill'),'WebGL 运行时已启动','good');
}
function resize(){const rect=$('viewport').getBoundingClientRect();state.renderer.setSize(Math.max(1,rect.width),Math.max(1,rect.height),false);state.camera.aspect=Math.max(1,rect.width)/Math.max(1,rect.height);state.camera.updateProjectionMatrix()}

async function fetchModel(){
  const response=await fetch('https://github.com/haihao0307/AIRCRAFT/releases/download/80-days-source-v1/b-24_liberator.glb',{cache:'no-store'});if(!response.ok)throw new Error(`模型下载失败，HTTP ${response.status}`);
  const total=Number(response.headers.get('content-length'))||LOCK.bytes;const reader=response.body?.getReader();
  if(!reader){const buffer=await response.arrayBuffer();progress(.72,'下载完成',buffer.byteLength);return buffer}
  const chunks=[];let received=0;while(true){const {done,value}=await reader.read();if(done)break;chunks.push(value);received+=value.byteLength;progress((received/total)*.72,`${Math.round(received/total*100)}%`,received)}
  const merged=new Uint8Array(received);let offset=0;for(const chunk of chunks){merged.set(chunk,offset);offset+=chunk.byteLength}return merged.buffer
}
async function verify(buffer){$('loadingText').textContent='下载完成，正在浏览器内计算 SHA256。';progress(.76,'计算 SHA256',buffer.byteLength);if(buffer.byteLength!==LOCK.bytes)throw new Error(`字节数不符：${buffer.byteLength}`);if(!crypto?.subtle)throw new Error('浏览器无法执行 SHA256 校验');const digest=hex(await crypto.subtle.digest('SHA-256',buffer));if(digest!==LOCK.sha256)throw new Error(`SHA256 不符：${digest}`);pill($('sourcePill'),'权威源文件校验通过','good');progress(.84,'源文件锁通过',buffer.byteLength)}
const parse=buffer=>new Promise((resolve,reject)=>new GLTFLoader().parse(buffer,'',resolve,reject));
function triangleCount(json){let total=0;for(const mesh of json.meshes||[])for(const primitive of mesh.primitives||[]){const i=primitive.indices??primitive.attributes?.POSITION;const count=json.accessors?.[i]?.count||0;const mode=primitive.mode??4;if(mode===4)total+=Math.floor(count/3);else if(mode===5||mode===6)total+=Math.max(0,count-2)}return total}
function validateInventory(gltf){const json=gltf.parser.json;const actual={scenes:(json.scenes||[]).length,nodes:(json.nodes||[]).length,meshes:(json.meshes||[]).length,triangles:triangleCount(json),materials:(json.materials||[]).length,images:(json.images||[]).length,animations:(json.animations||[]).length,animationChannels:(json.animations||[]).reduce((n,a)=>n+a.channels.length,0)};for(const key of Object.keys(actual))if(actual[key]!==LOCK[key])throw new Error(`清单 ${key} 不符：${actual[key]}，预期 ${LOCK[key]}`);for(const [id,key] of [['sceneCount','scenes'],['nodeCount','nodes'],['meshCount','meshes'],['triangleCount','triangles'],['materialCount','materials'],['imageCount','images'],['animationCount','animations'],['channelCount','animationChannels']])$(id).textContent=actual[key].toLocaleString();return actual}

function buildRecords(gltf){const json=gltf.parser.json;state.records=[];state.recordByObject.clear();gltf.scene.traverse(object=>{const association=gltf.parser.associations.get(object);const index=association?.nodes;if(index===undefined)return;const source=json.nodes[index]||{};const record={index,object,name:source.name||object.name||`node_${index}`,type:object.isMesh?'Mesh':object.isBone?'Bone':object.type||'Object3D',mesh:source.mesh??null};state.records.push(record);state.recordByObject.set(object,record)});state.records.sort((a,b)=>a.index-b.index);renderNodes('')}
function remember(){state.root.traverse(object=>{state.visibility.set(object,object.visible);if(object.isMesh){const materials=Array.isArray(object.material)?object.material:[object.material];for(const material of materials)if(material&&!state.wireframes.has(material))state.wireframes.set(material,material.wireframe===true)}})}
function mount(gltf){
  validateInventory(gltf);state.root=gltf.scene;state.wrapper=new THREE.Group();state.wrapper.name='display_wrapper_only';state.wrapper.add(state.root);state.scene.add(state.wrapper);state.root.updateMatrixWorld(true);
  const sourceBox=new THREE.Box3().setFromObject(state.root);const center=sourceBox.getCenter(new THREE.Vector3());state.wrapper.position.copy(center).multiplyScalar(-1);state.wrapper.updateMatrixWorld(true);const box=new THREE.Box3().setFromObject(state.wrapper);const sphere=box.getBoundingSphere(new THREE.Sphere());state.grid.position.y=box.min.y-Math.max(.01,sphere.radius*.015);
  buildRecords(gltf);remember();
  if(gltf.animations.length){state.clip=gltf.animations[0];state.mixer=new THREE.AnimationMixer(state.root);state.action=state.mixer.clipAction(state.clip);state.action.setLoop(THREE.LoopRepeat,Infinity);state.action.play();state.action.paused=true;$('timeline').disabled=false;$('timeline').max=String(state.clip.duration);$('timeEnd').textContent=state.clip.duration.toFixed(2)}
  view('perspective');progress(1,'装载完成',LOCK.bytes);$('loadingText').textContent='源文件锁、模型清单与浏览器运行时均已通过。';setTimeout(()=>$('loading').classList.add('hidden'),260);pill($('runtimePill'),'精确参考模型已装载','good');document.body.dataset.qa='pass';window.__B24_REFERENCE_QA={sourceSha256:LOCK.sha256,sourceBytes:LOCK.bytes,inventory:{nodes:LOCK.nodes,meshes:LOCK.meshes,triangles:LOCK.triangles,animationChannels:LOCK.animationChannels},visualParityApproved:false,animationSemanticsApproved:false}}
function fit(object=state.wrapper,direction=new THREE.Vector3(1.15,.72,1.22).normalize()){if(!object)return;const box=new THREE.Box3().setFromObject(object);if(box.isEmpty())return;const sphere=box.getBoundingSphere(new THREE.Sphere());const distance=Math.max(sphere.radius,.01)/Math.sin(THREE.MathUtils.degToRad(state.camera.fov)/2)*1.12;state.camera.position.copy(sphere.center).addScaledVector(direction,distance);state.camera.near=Math.max(.001,distance/5000);state.camera.far=Math.max(100,distance*20);state.camera.updateProjectionMatrix();state.controls.target.copy(sphere.center);state.controls.update()}
function view(id){if(!state.wrapper)return;const dirs={perspective:new THREE.Vector3(1.15,.72,1.22).normalize(),'x+':new THREE.Vector3(1,0,0),'x-':new THREE.Vector3(-1,0,0),'y+':new THREE.Vector3(0,1,.0001).normalize(),'y-':new THREE.Vector3(0,-1,.0001).normalize(),'z+':new THREE.Vector3(0,0,1),'z-':new THREE.Vector3(0,0,-1)};state.camera.up.set(0,1,0);if(id==='y+'||id==='y-')state.camera.up.set(0,0,id==='y+'?-1:1);fit(state.wrapper,dirs[id]||dirs.perspective);document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===id))}

function kind(record){if(record.object.isMesh)return record.mesh===null?'mesh':`mesh ${record.mesh}`;if(record.object.children.length)return `${record.object.children.length} 子节点`;return record.type}
function renderNodes(query){const q=query.trim().toLowerCase();const records=state.records.filter(r=>q?r.name.toLowerCase().includes(q)||String(r.index).includes(q)||r.type.toLowerCase().includes(q)||String(r.mesh??'').includes(q):r.object.isMesh||r.object.children.length);$('nodeResultCount').textContent=`${records.length.toLocaleString()}，显示前 ${Math.min(records.length,160)}`;const fragment=document.createDocumentFragment();for(const record of records.slice(0,160)){const button=document.createElement('button');button.className=`node-item${state.selected===record?' active':''}`;button.innerHTML=`<span class="node-index">${record.index}</span><span class="node-name" title="${esc(record.name)}">${esc(record.name)}</span><span class="node-kind">${esc(kind(record))}</span>`;button.onclick=()=>select(record);fragment.append(button)}$('nodeList').replaceChildren(fragment)}
const vector=v=>`${v.x.toFixed(4)}, ${v.y.toFixed(4)}, ${v.z.toFixed(4)}`;
function select(record){state.selected=record;state.boxHelper.setFromObject(record.object);state.boxHelper.visible=!new THREE.Box3().setFromObject(record.object).isEmpty();$('selectedIndex').textContent=record.index;$('selectedName').textContent=record.name;$('selectedType').textContent=kind(record);const parent=record.object.parent?state.recordByObject.get(record.object.parent):null;$('selectedParent').textContent=parent?`${parent.index} · ${parent.name}`:record.object.parent?.name||'场景根';$('selectedChildren').textContent=record.object.children.length;const p=record.object.getWorldPosition(new THREE.Vector3());$('selectedPosition').textContent=vector(p);const box=new THREE.Box3().setFromObject(record.object);$('selectedBounds').textContent=box.isEmpty()?'无可见几何':vector(box.getSize(new THREE.Vector3()));$('isolateBtn').disabled=false;$('hideBtn').disabled=false;$('focusBtn').disabled=box.isEmpty();renderNodes($('nodeSearch').value)}
function pick(event){if(!state.root)return;const rect=$('canvas').getBoundingClientRect();state.pointer.x=(event.clientX-rect.left)/rect.width*2-1;state.pointer.y=-(event.clientY-rect.top)/rect.height*2+1;state.raycaster.setFromCamera(state.pointer,state.camera);const hits=state.raycaster.intersectObject(state.root,true);if(!hits.length)return;let object=hits[0].object;while(object&&!state.recordByObject.has(object))object=object.parent;const record=object?state.recordByObject.get(object):null;if(record)select(record)}
function restore(){for(const [object,visible] of state.visibility)object.visible=visible;state.boxHelper.visible=Boolean(state.selected)}
function isolate(){if(!state.selected)return;state.root.traverse(object=>object.visible=!object.isMesh);state.selected.object.traverse(object=>object.visible=true);let parent=state.selected.object.parent;while(parent){parent.visible=true;parent=parent.parent}state.boxHelper.visible=true}
function hide(){if(!state.selected)return;state.selected.object.visible=false;state.boxHelper.visible=false}
function setWire(enabled){for(const [material,original] of state.wireframes)material.wireframe=enabled||original}
function play(value){if(!state.action)return;state.playing=value;state.action.paused=!value;$('playBtn').textContent=value?'暂停':'播放';$('playBtn').classList.toggle('active',value)}
function updateTime(){if(!state.action||!state.clip)return;const time=Math.max(0,Math.min(state.clip.duration,state.action.time||0));$('timeline').value=time;$('timeNow').textContent=time.toFixed(2)}

function events(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>view(b.dataset.view));$('fitBtn').onclick=()=>fit();$('wireToggle').onchange=e=>setWire(e.target.checked);$('axesToggle').onchange=e=>state.axes.visible=e.target.checked;$('gridToggle').onchange=e=>state.grid.visible=e.target.checked;$('rotateToggle').onchange=e=>state.controls.autoRotate=e.target.checked;$('exposure').oninput=e=>state.renderer.toneMappingExposure=Number(e.target.value);$('playBtn').onclick=()=>play(!state.playing);$('stopBtn').onclick=()=>{if(!state.mixer)return;play(false);state.mixer.setTime(0);state.action.time=0;updateTime()};$('timeline').oninput=e=>{if(!state.mixer)return;play(false);const time=Number(e.target.value);state.mixer.setTime(time);state.action.time=time;updateTime()};$('speed').onchange=e=>state.speed=Number(e.target.value);$('loopToggle').onchange=e=>{if(!state.action)return;state.action.setLoop(e.target.checked?THREE.LoopRepeat:THREE.LoopOnce,e.target.checked?Infinity:1);state.action.clampWhenFinished=!e.target.checked};$('nodeSearch').oninput=e=>renderNodes(e.target.value);$('isolateBtn').onclick=isolate;$('hideBtn').onclick=hide;$('restoreBtn').onclick=restore;$('focusBtn').onclick=()=>state.selected&&fit(state.selected.object);$('leftToggle').onclick=()=>$('leftPanel').classList.toggle('open');$('rightToggle').onclick=()=>$('rightPanel').classList.toggle('open')}
async function buildInfo(){try{const response=await fetch('./build-info.json',{cache:'no-store'});if(!response.ok)return;const info=await response.json();$('buildBranch').textContent=info.branch||'未知';$('buildCommit').textContent=info.commit||'未知';$('buildTime').textContent=info.built_at||'未知'}catch(error){console.warn(error)}}
function loop(){requestAnimationFrame(loop);const delta=Math.min(state.clock.getDelta(),.05);if(state.mixer&&state.playing){state.mixer.update(delta*state.speed);updateTime()}if(state.selected&&state.boxHelper.visible)state.boxHelper.update();state.controls.update();state.renderer.render(state.scene,state.camera)}
async function boot(){try{initScene();events();loop();buildInfo();const buffer=await fetchModel();await verify(buffer);$('loadingText').textContent='校验通过，正在解析 1,784 个节点和 2,518 条动画通道。';progress(.88,'解析 GLB',buffer.byteLength);const gltf=await parse(buffer);progress(.94,'验证模型清单',buffer.byteLength);mount(gltf)}catch(error){fail(error)}}
boot();
