#!/usr/bin/env python3
from pathlib import Path
import json,threading,http.server,functools,time
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).resolve().parents[1]
server=http.server.ThreadingHTTPServer(('127.0.0.1',8765),functools.partial(http.server.SimpleHTTPRequestHandler,directory=str(ROOT/'runtime')))
threading.Thread(target=server.serve_forever,daemon=True).start()
report={'checks':[],'viewports':[],'visualAcceptance':False,'productionReady':False}
def check(name,value):
    report['checks'].append({'name':name,'passed':bool(value)})
    if not value: print('FAILED',name)
with sync_playwright() as p:
    browser=p.chromium.launch(headless=True,args=['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader'])
    for width,height in [(1440,900),(390,844)]:
        page=browser.new_page(viewport={'width':width,'height':height});errors=[]
        page.on('pageerror',lambda e:errors.append(str(e)))
        page.on('console',lambda m:errors.append(m.text) if m.type=='error' else None)
        page.goto('http://127.0.0.1:8765/',wait_until='domcontentloaded')
        page.wait_for_function('window.__B24_WORKBENCH__?.productionEffects?.ready',timeout=150000)
        page.wait_for_timeout(1500)
        print('READY',width,page.evaluate('window.__B24_WORKBENCH__.productionEffects.audit()'))
        a=page.evaluate('window.__B24_WORKBENCH__.productionEffects.audit()')
        check(f'{width} tire selection',a['surfaceCounts']['tire']==7)
        check(f'{width} skin selection',a['surfaceCounts']['skin']>0)
        check(f'{width} four source rotor channels',len(a['rotorChannels'])==4)
        check(f'{width} geometry references',a['sourceGeometryPreserved'])
        page.evaluate('''()=>{const a=window.__B24_WORKBENCH__;window.__frozen={parents:a.plane.nodes.map(n=>n.parent?.uuid),geometries:a.plane.geometries.map(g=>g.uuid)};a.pause();a.seek(121); }''')
        page.wait_for_timeout(700)
        q1=page.evaluate('window.__B24_WORKBENCH__.effects.bombs[0].o.quaternion.toArray()')
        page.wait_for_timeout(400)
        q2=page.evaluate('window.__B24_WORKBENCH__.effects.bombs[0].o.quaternion.toArray()')
        check(f'{width} paused roll stable',q1==q2)
        a=page.evaluate('window.__B24_WORKBENCH__.productionEffects.audit()');check(f'{width} roll visible',a['lastRoll']>0)
        page.evaluate('window.__B24_WORKBENCH__.seek(122)');page.wait_for_timeout(400)
        q3=page.evaluate('window.__B24_WORKBENCH__.effects.bombs[0].o.quaternion.toArray()');check(f'{width} roll advances',q3!=q1)
        page.evaluate('window.__B24_WORKBENCH__.seek(60)');page.wait_for_timeout(500)
        active=page.evaluate("(()=>{let n=0;window.__B24_WORKBENCH__.scene.traverse(o=>{if(o.name==='B24_SOURCE_BLADE_EXPOSURE'&&o.visible)n++});return n;})()")
        check(f'{width} blur active',active>0)
        page.screenshot(path=str(ROOT/f'reports/flight-{width}.png'))
        page.evaluate('window.__B24_WORKBENCH__.productionEffects.setEnabled(false)');page.wait_for_timeout(300)
        check(f'{width} A/B toggle',page.evaluate('!window.__B24_WORKBENCH__.productionEffects.enabled'))
        page.evaluate('window.__B24_WORKBENCH__.productionEffects.setEnabled(true)')
        phases=[]
        for t in [0,5,20,30,45,58,80,100,115,121,129,150,175,190,205,218,270,326]:
            page.evaluate('(t)=>{window.__B24_WORKBENCH__.seek(t);}',t);page.wait_for_timeout(100)
            phases.append(page.evaluate('window.__B24_WORKBENCH__.getState().phase'))
        check(f'{width} eighteen phases',len(set(phases))==18)
        page.evaluate('window.__B24_WORKBENCH__.seek(150)');page.wait_for_timeout(200)
        check(f'{width} four releases impacts',page.evaluate('(()=>{const s=window.__B24_WORKBENCH__.getState();return s.released===4&&s.impacts===4;})()'))
        impact=page.evaluate('window.__B24_WORKBENCH__.effects.lastImpact')
        page.evaluate('(t)=>{const a=window.__B24_WORKBENCH__;a.setCamera("cinema");a.seek(t+.25);}',impact);page.wait_for_timeout(300)
        check(f'{width} impact shot framed',page.evaluate('window.__B24_WORKBENCH__.productionEffects.impactFramed'))
        page.screenshot(path=str(ROOT/f'reports/impact-{width}.png'))
        page.evaluate('window.__B24_WORKBENCH__.setCamera("front")');page.wait_for_timeout(300)
        check(f'{width} manual camera respected',page.evaluate('!window.__B24_WORKBENCH__.productionEffects.impactFramed'))
        page.evaluate('window.__B24_WORKBENCH__.reset()');page.wait_for_timeout(500)
        check(f'{width} reset',page.evaluate('(()=>{const a=window.__B24_WORKBENCH__;return a.getState().time===0&&a.effects.bombs.length===0&&a.productionEffects.lastRoll===0;})()'))
        check(f'{width} original parent graph unchanged',page.evaluate('JSON.stringify(__frozen.parents)===JSON.stringify(__B24_WORKBENCH__.plane.nodes.map(n=>n.parent?.uuid))'))
        check(f'{width} original geometry unchanged',page.evaluate('JSON.stringify(__frozen.geometries)===JSON.stringify(__B24_WORKBENCH__.plane.geometries.map(g=>g.uuid))'))
        check(f'{width} no weather or fog',page.evaluate('__B24_WORKBENCH__.scene.fog===null&&!__B24_WORKBENCH__.productionEffects.weather'))
        check(f'{width} no browser error',not errors and page.evaluate('__B24_WORKBENCH__.errors.length===0'))
        check(f'{width} no horizontal overflow',page.evaluate('document.documentElement.scrollWidth<=innerWidth+1'))
        frames0=page.evaluate('__B24_WORKBENCH__.frameCount');page.wait_for_timeout(2000);frames1=page.evaluate('__B24_WORKBENCH__.frameCount')
        check(f'{width} rendering advances',frames1>frames0)
        report['viewports'].append({'width':width,'height':height,'errors':errors,'audit':page.evaluate('__B24_WORKBENCH__.productionEffects.audit()'),'frames_in_2s':frames1-frames0,'renderer':page.evaluate('(()=>{const g=__B24_WORKBENCH__.renderer.getContext();return g.getParameter(g.RENDERER);})()')})
        page.close()
    browser.close()
server.shutdown()
report['passed']=all(c['passed'] for c in report['checks']);report['passed_count']=sum(c['passed'] for c in report['checks']);report['total']=len(report['checks'])
(ROOT/'reports/BROWSER_QA.json').write_text(json.dumps(report,indent=2))
print('BROWSER_QA_REPORT',json.dumps(report))
raise SystemExit(0 if report['passed'] else 1)
